### PR TITLE
fix(datepicker): remove `new Date` fallback

### LINKED ISSUE #1289: date picker dd.MM.yyyy
hi there, i'm testing the datepicker within angular 1.2.2 and bs 3 using our common swiss (and german) date format dd.MM.yyyy
just recognised that entering the date value manually in the textbox does not work as expected. it still uses the first number as the month.

http://plnkr.co/edit/1pdDca5KuWOWh3vPVRvz?p=preview

### PR DESCRIPTION
**Pull request by wesleycho**
- Remove `new Date` fallback due to buggy behavior

[Here](http://plnkr.co/edit/SygiafItpeq2S1m1Nb50?p=preview) is a working Plunker with the change.

This closes #2513, #3294, #3344, and #3682, and fixes #1289, #2446, #3037, #3104, #3196, #3206, #3342, #3617, #3644

### CODE REVIEW

**Comment by chrisirhc** [comment]
I'm all for this changing. I didn't do it at first because it was a breaking change.

**Comment by chrisirhc** [comment]
LGTM

**Comment by chrisirhc** [comment]
Commit message should have "BREAKING CHANGE" and a description

**Comment by wesleycho** [comment]
Ah crap, forgot to put this PR # in the commit message - it is merged as of https://github.com/angular-ui/bootstrap/commit/ab4580fd81582cde5fd869c87cc4366cdc7f534d

**Pull request closed without merging**
