### PR TITLE
fix(tooltip): Fix animation when ngAnimate is present

### PR DESCRIPTION
**Pull request by wesleycho**
- This disables ngAnimate's animation on the tooltip element due to $animate interfering with Bootstrap's transitions

Plunker of fix in action [here](http://plnkr.co/edit/6Hqw29jlscL9k9HH6CSW?p=preview)

This addresses #3375.

### CODE REVIEW

**Comment by chrisirhc** [comment]
Note that we need to upgrade the rest of angular test libs to the same version otherwise we might encounter weirdness in the tests.

Also, instead of disabling the animation on the tooltip completely, we can use the .css approach in https://github.com/angular-ui/bootstrap/pull/2699 , with carousel.css setting up transition values of 0. That's another approach that allows users use other animations if they want.

**Comment by chrisirhc** [comment]
Also, we're using lowercase for module names: fix(tooltip) . That's just for grunt-conventional-changelog to pick things up correctly.

**Comment by wesleycho** [comment]
Ahh, I was not aware of that work - that would be a lot nicer.  I had meant for this to be a stop gap solution that at least fixes the breaking problem until we got to making it truly ngAnimate compatible.

I'll review #2699 when I get home.

**Comment by wesleycho** [comment]
Closing this, will revisit with a more ngAnimate compatible approach.

**Pull request closed without merging**
