### PR TITLE
feat(dropdown): add nesting capability

### PR DESCRIPTION
**Pull request by sebastianhenneberg**
Adds nesting support for dropdowns as discussed in #2421. Allows to reflect deep hierarchies using dropdowns. The implementation uses an array as a stack to keep track of opened dropdown scopes.

### CODE REVIEW

**Comment by RobJacobs** [comment]
@sebastianhenneberg There is a css solution for implementing this feature [here](http://bootsnipp.com/snippets/featured/multi-level-dropdown-menu-bs3)

**Comment by sebastianhenneberg** [comment]
@RobJacobs I have seen the CSS solution in the issue already. You get this with pure bootstrap (without angular-ui/bootstrap). I required a solution that utilizes the dropdown directive and allows me to customize the behaviour.

**Comment by wesleycho** [comment]
I am not sure we want to support something like this due to poor UX, although if I remember correctly, Bootstrap also had some controversy related to this as well.

**Comment by wesleycho** [comment]
Closing as per https://github.com/angular-ui/bootstrap/issues/2421#issuecomment-140869946

**Pull request closed without merging**
