### PR TITLE
fix(dropdown): restored deprecated directives

### PR DESCRIPTION
**Pull request by BobbieBarker**

### CODE REVIEW

**Comment by Foxandxss** [comment]
Better, the if checks for deprecation, move them to the beginning of the link function (as we do in the others). Also, when this gets merged (/me looks to Wes), change fix for chore, we don't need this on changelog.

**Comment by Foxandxss** [comment]
Also, there is an old commit in here, I am not sure if that is gonna blow or not. Damn git.

**Comment by wesleycho** [comment]
That commit screws up history - this is not mergeable.

**Comment by wesleycho** [comment]
I fixed everything in #4514.

**Comment by Foxandxss** [comment]
Thanks Wes.

**Pull request closed without merging**
