### PR TITLE
feat(typeahead): Typeahead Custom Popup Template support

### PR DESCRIPTION
**Pull request by tthew**
Provides support for custom popup template for `typeahead` directive.  Introduces new `typeahead-popup-template-url` attribute to `typeahead` directive.

### CODE REVIEW

**Comment by tthew** [comment]
Tests are failing, but they also seem to be failing if I run them from `angular-ui:master`.

**Comment by tthew** [comment]
So, tests are failing on: 

```shell
Chrome 40.0 (Mac) typeahead tests basic functionality should open and close typeahead based on matches FAILED
	Expected undefined to be 'typeahead-CD7-418'.
	Error: Expected undefined to be 'typeahead-CD7-418'.
	    at null.<anonymous> (src/typeahead/test/typeahead.spec.js:146:48)
Chrome 40.0 (Mac): Executed 663 of 663 (1 FAILED) (22.706 secs / 22.45 secs)
```

...and I'm a little confused as to why.  Any insight would be greatly appreciated!

**Comment by TalD** [comment]
Any plans to get this merged in? I think this is super useful.

**Comment by wesleycho** [comment]
Closing, as we already do have support for custom popup templates with `typeahead-popup-template-url`

**Pull request closed without merging**
