### PR TITLE
Optional autofocus on typeahead selection

### PR DESCRIPTION
**Pull request by angi-**
There are some issues when you want an input to clear value on focus and after selection it gets cleared again because of the autofocus. I added an optional parameter for autofocus on selection, it is disabled by default.

### CODE REVIEW

**Comment by wesleycho** [comment]
Can you squash your commits?

Scheduling this for 0.13.1, this just needs documentation updates.

**Comment by angi-** [comment]
I have done this on another pull request, I also created automated tests: https://github.com/angular-ui/bootstrap/pull/3211

Let me know if I can further help to get this update in the next release.

**Comment by karianna** [comment]
@angi- So should we close this PR?

**Comment by wesleycho** [comment]
This just needs documentation updates and it should be good to go.

**Comment by wesleycho** [comment]
Closing, as it has been superceded by #4212.

**Pull request closed without merging**
