### PR TITLE
docs(tabs): get rid of 'active' option on uib-tab directive

### PR DESCRIPTION
**Pull request by bryanbak**
The "active" option no longer exists for the uib-tab directive. It has been moved to uib-tabset. Looks like this little piece of documentation didn't get updated to remove it whenever this change was made.

### CODE REVIEW

**Comment by deeg** [comment]
Can you give a bit of a description about why you are making this change for people who are going to review it?

**Comment by bryanbak** [comment]
@deeg Description has been added

**Comment by icfantv** [comment]
I believe this is already fixed in master?

**Comment by icfantv** [comment]
Ah, no.  Different template.

**Comment by icfantv** [comment]
@deeg, this is fine to merge.

**Pull request closed without merging**
