### PR TITLE
fix(modal): add `$animateCss` support

### PR DESCRIPTION
**Pull request by wesleycho**
- Add support for `$animateCss`

The carousel change is to safely detect whether $animateCss is truly present (if the user is not using `ngAnimate`, then this would throw an exception before this patch.

The modal change is to correctly use `$animateCss` - this can be observed in action [here](http://plnkr.co/edit/75rLxCoDUlh1r6ecehVX?p=preview).

I am currently still investigating #4119, and hopefully will be able to patch that up on top of this or as a part of this PR. These changes are not enough to fix the broken behavior, as can be seen [here](http://plnkr.co/edit/Oi7YsUHB1QTIXSTb2GqC?p=preview).

### CODE REVIEW

**Comment by wesleycho** [comment]
I updated the Plunker, with usage from the snapshot version of Angular, due to a major ngAnimate fix that is currently not released. This is still currently broken in 1.4.3, but only with the indicators and controls being missing.

**Comment by icfantv** [comment]
LGTM

**Comment by mattlewis92** [comment]
FYI you can use `$injector.has('$animateCss')` instead of using the try catch to detect if $animateCss is available

**Comment by wesleycho** [comment]
I should have checked the docs...I never knew that existed - thanks for that tidbit, I will refactor that now.

**Pull request closed without merging**
