### PR TITLE
chore(karma): add coverage

### PR DESCRIPTION
**Pull request by Foxandxss**
The library was in place, it just needed a bit of love.

Used the dist folder for not creating yet another temporary root folder.

### CODE REVIEW

**Comment by wesleycho** [comment]
LGTM - guess this means that I have to be a little careful when I copy/paste when doing a release, but that's ok.

**Comment by wesleycho** [comment]
Actually, maybe it would be better to gitignore a `.coverage` folder and put it there, just to avoid polluting contents.

**Comment by Foxandxss** [comment]
Sure.

**Comment by Foxandxss** [comment]
Done.

Out of curiosity, we also add an entry in the gitignore :P

**Pull request closed without merging**
