### PR TITLE
fix(tooltip): remove when body is clicked

### PR DESCRIPTION
**Pull request by petebacondarwin**

### CODE REVIEW

**Comment by wesleycho** [comment]
I agree, this should be configurable.

**Comment by karianna** [comment]
@petebacondarwin Can you also rebase with master please.

**Comment by smoakey** [comment]
I like this functionality but wouldnt it also hide when you click inside the popover itself. Id like for it to only go away when clicking elsewhere.

**Comment by petebacondarwin** [comment]
Things in master seem to have changed quite a lot. Is this PR still relevant?

**Comment by wesleycho** [comment]
We don't have this implemented yet, but probably best to just have this done from scratch based on current master IMO

**Comment by icfantv** [comment]
OMG! It's a @petebacondarwin sighting!  :-)

**Comment by petebacondarwin** [comment]
Sorry guys, I've been a bit busy recently :-/

**Comment by wesleycho** [comment]
Leading Angular 1 development will do that to you :)

**Comment by icfantv** [comment]
Don't sweat it, dude.  It's all good.

**Pull request closed without merging**
