### PR TITLE
fix(tabs): adding 'active' ng-class for tab <a> tags for bootstrap 4

### PR DESCRIPTION
**Pull request by uxtx**
- adds 'active'/'disabled' classes for anchor links to affect proper active tab styling in bootstrap 4.

### CODE REVIEW

**Comment by Foxandxss** [comment]
We are not giving BS 4 support at this moment.

**Comment by icfantv** [comment]
@foxandxss, @wesleycho allowed a PR in last week or so.  IMO, if the change doesn't break anything and doesn't add bloat, I don't have an issue with it.  Thoughts, guys?

**Comment by Foxandxss** [comment]
I don't have an issue as well, I just don't want to give the false impression that we are supporting BS4

**Comment by uxtx** [comment]
I'll work to address any regressions that get reported.  To my knowledge the active toggle class on anchor tags, along with the 'nav-link' class on the anchor tag are all that are needed for bs4, and I didn't notice any real negatives to including these tags in existant bootstrap versions.

**Comment by uxtx** [comment]
I do know bs4 makes more sense going forward for ng2, but my feeling (with tabs at least) was that this was low hanging fruit to get to a minimal level of functionality.

**Comment by wesleycho** [comment]
This adds a $watch from ng-class - I do not think this is wise while support Bootstrap 3. The `nav-link` class is fine because it is a harmless change, but this has perf ramifications.

I'm inclined to reject this.

**Comment by uxtx** [comment]
I suppose that makes sense. I could look at possibly using a different template for BS4 that would remove the duplicated watch, if that'd be preferred. but that may mean enlarging the scope of the pr beyond what the team would desire. Any suggestions?

**Comment by wesleycho** [comment]
At this time, I think you should just override the default template with your own template in $templateCache.

When we investigate BS4 support, we can then make the modifications, but that won't be for a little while.

**Pull request closed without merging**
