### PR TITLE
feat(dateparser): optional leading '0' for 'M' and 'd' dateparser format

### PR DESCRIPTION
**Pull request by loicoudot**
Fix for issue #2812

### CODE REVIEW

**Comment by yankee42** [comment]
After some mysterious debugging on an application I wrote why on the issue that some people were just not able to input their birthday I figured that what you describe here is the reason. It worked for some people because they entered dates with preceding zeros or used the date picker dialogue while others did not and I did not test this either.

The behaviour feels unnatural and the only solution would be to tell users that they either must or must not enter their birthday with preceding zeros.

I manually applied @chrisirhc patch (except that I changed the regex for `dd` and `mm` rather than `d` and `m`) and it does seem to work perfectly. I agree with @Garios that parsing for `dd` should be the same as for `d`. Because really... who would expect that failing to specify a leading zero is an error. However I'd also be OK with switching to just `d` in all my date fields...

Anyway: Is there still an issue with that patch? So far nobody disagrees with the patch (except for the discussion whether this patch should be extended even further) or did I miss anything. I would really love to see this resolved :-).

**Comment by wesleycho** [comment]
I think this would need a documentation change so that users of the datepicker know what to expect here.

**Comment by nipec** [comment]
Hi, I need this feature for my project - how can I help to get it into the next release?

**Comment by wesleycho** [comment]
Closing, as the implementation is currently flawed - this needs to be opt-in.

Track this feature request in #4805, hoping to have an implementation ready sometime this week.

**Pull request closed without merging**
