### PR TITLE
feat(timepicker): add seconds support

### PR DESCRIPTION
**Pull request by cgat**
Updating this PR(https://github.com/angular-ui/bootstrap/pull/3022) in hopes that it gets merged. Relevant to this issue: https://github.com/angular-ui/bootstrap/issues/2326

### CODE REVIEW

**Comment by wesleycho** [comment]
Can you please squash your commits and rebase?

**Comment by cgat** [comment]
@wesleycho it is hidden behind an opt-in flag. To use it, the 'show-seconds' attribute needs to be set to true. Take a look at timepicker.js. showSeconds is set to false by default (seach "showSeconds: false").

I will squash.

**Comment by hdngr** [comment]
+1

**Comment by icfantv** [comment]
@hdngr, please do not just +1 issues.  It does not add any inherent value and clutters up issues.  Thank you.

**Comment by cgat** [comment]
Working on something else at the moment, will try to squash this week.

**Comment by cgat** [comment]
Hey, I finally got around to this. When I pull from angular-ui/bootstrap master and run `grunt`, I see a bunch of failing tests. Is this expected? Should are be merging master into my branch or something more stable?

**Comment by wesleycho** [comment]
`master` should be fine, which might mean that you might have resolved the conflicts incorrectly.

Also be sure to run `npm update` to make sure your node modules are up to date (just in case).

**Comment by icfantv** [comment]
@cgat, if it's been a while, the best thing might be to blow away your `node_modules` directory and run `npm install` again.  That will clear out all the cobwebs.

**Comment by cgat** [comment]
Thanks guys, npm update did the trick.

**Comment by ima-tech** [comment]
If you guys could add that it would be amazin.

**Comment by icfantv** [comment]
@cgat, any update?  apparently you have a fan.

**Comment by cgat** [comment]
@icfantv sorry, life has been busy (child on the way). Update: last time I went back to this I realized I was further off upstream than I thought. I've been able to rebase, but a couple tests aren't passing (though the functionality seems right). I'll see if I can carve out a bit of time this weekend to work on it, but can't make any guarantees.  If I don't make any head way, I may ask for help.

**Comment by icfantv** [comment]
@cgat, sound good.  I have two kids so I fully understand (and just wait, you think your life is full now?...).

**Comment by cgat** [comment]
I've resubmitted with proper merge squash here https://github.com/angular-ui/bootstrap/pull/4725 (ended up being easier than updating this one... I was fighting with git a lot).

Side note: how do you guys merge your PRs with getting the default "Merge" commit that is given by github. I'm working on another project and we'd like to follow a similar pattern, but whenever we merge a PR, the title of the merge is uneditable, thus we don't get to keep the nice "feat(scope): subject... body" commit size in master.

**Comment by PanfilovDenis** [comment]
what about creating new bower version with this feature?

**Comment by wesleycho** [comment]
We have some release blockers - keep an eye on #4838.

**Pull request closed without merging**
