### PR TITLE
feat(accordion): use .value() for uibAccordionConfig

### PR DESCRIPTION
**Pull request by wesleycho**

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
What is a motivation for this / other changes like this?

**Comment by wesleycho** [comment]
Being able to override via `.decorator()`

**Comment by pkozlowski-opensource** [comment]
> Being able to override via .decorator()

The potential downside being that it is no longer injectable in providers, if this matters,,,,

**Comment by wesleycho** [comment]
Hmm, so I guess it technically is a breaking change. Hmm...I feel like the main reason it is used is to override our defaults with the user specified ones, but I guess someone could be using it to configure app wide settings.

IMO it should have always been .value, but it seems it's too late now. Probably should close all my PRs then, and need to revert the commit of the dropdown one.

**Pull request closed without merging**
