### PR TITLE
Allow string as Tab index value

### PR DESCRIPTION
**Pull request by vadim-p**
Simple situation - when iterating hash, so hash key plays well as index.

### CODE REVIEW

**Comment by icfantv** [comment]
@vadim-p, i'm ok with this, but this is going to need tests and a documentation update as well.

**Comment by icfantv** [comment]
@vadim-p, this is a good feature, but we are unable to use this PR and will close it if you don't address the concerns previously mentioned.  Thanks.

**Comment by RobJacobs** [comment]
We are also doing the isNumber check in the select and addTab functions.  I'd like to get an opinion from @wesleycho on whether the index needs to be a number or we can just use isDefined instead?

**Comment by wesleycho** [comment]
I assumed an index should be a number - I'm not hugely opinionated on whether it should be though, and am fine with changing that. @icfantv is right in what this PR needs though.

**Comment by vadim-p** [comment]
Hello. Sorry for silence from my side - I'm traveling. I'll try to get back to you with updates in 3-4 days. Thank you.

**Comment by icfantv** [comment]
@vadim-p, awesome.  Thanks.

**Comment by icfantv** [comment]
@vadim-p do you still intend on completing this?  If not, we're going to close it.

**Comment by icfantv** [comment]
Closing due to lack of response.  Replaced by #5713.

**Pull request closed without merging**
