### PR TITLE
Show / Hide control arrows around timepicker

### PR DESCRIPTION
**Pull request by BenjaminCh**
Add an optionnal parameter on timepicker object in order to control the visibility of the controls arrows.

### CODE REVIEW

**Comment by wesleycho** [comment]
The history needs to be cleaned up on this PR.

**Comment by jnels124** [comment]
is this PR ever going to be accepted?

**Comment by rvanbaalen** [comment]
Not sure if we should. Why not add your own custom template or css to achieve this goal?

**Comment by wesleycho** [comment]
It looks like this is already in `master` in a form with `show-spinners`.

**Pull request closed without merging**
