### PR TITLE
fix(tooltip): popup close delay not respected

### PR DESCRIPTION
**Pull request by RobJacobs**
Under PR #4455 the timeout for the popup close delay
was impacted by the evalAsync for setting the isOpen
value.  Moved the popup close delay timeout to the
hideTooltipBind method so the hide mehtod will now
get called after the close popup delay.  This will
also ensure if the show method is called and the
close timeout is cancelled, the isOpen property
will not get toggled.

### CODE REVIEW

**Comment by wesleycho** [comment]
Can you explain what is going on here - how come it is not enough that all of the logic is in the hide function and why move it up to the `hideTooltipBind` function?

**Comment by RobJacobs** [comment]
The hide function is called in the disabled and empty content watchers, by-passing the close delay. Maybe they shouldn't?

**Comment by RobJacobs** [comment]
@tmcgee123 @wesleycho After looking into this further, I think the original implementation of this feature was wrong.  The transitionTimeout should be reserved for allowing the tooltip animation to run before removing the tooltip element from the dom.  The tooltip templates use ng-class="{ in: isOpen() }" to add and remove the 'in' class which sets the opacity (0 and .9).  The fade class has the opactiy transition with a time of .15s.

A close delay should be a different timeout that completes before the transitionTimeout.  I'm going to do some more work on this PR and get this working as it should.

**Comment by tmcgee123** [comment]
@RobJacobs I agree. Originally in 13.x, the functionality was as you said. But, with the updates that were put through, it looks as though the timeout is no longer completing before the animation starts.

**Comment by wesleycho** [comment]
This PR LGTM - that was a good find that the implementation was incorrect. We really need to port the timeout to use ngAnimate, but that's future work.

**Pull request closed without merging**
