### PR TITLE
Update accordion-group.html to support click operation on accordion-heading

### PR DESCRIPTION
**Pull request by ramana-chavakula**
adding href="javascript:void(0)" which will stop the page to reload if we add any click operation on accordion-heading

### CODE REVIEW

**Comment by wesleycho** [comment]
Please post an issue with minimal reproduction in Plunker - this code is a CSP violation, which is a major no-go.

**Comment by ramana-chavakula** [comment]
hi wesleycho,
here is my plunker http://plnkr.co/edit/hZq4daZGzWmIawAl71d0?p=preview
if you click on checkbox in the accordian-header it's triggering a reload of the page in firefox. I thought it's a fix but it's triggering a CSP violation :( 
Thanks for your info 👍

**Comment by wesleycho** [comment]
I don't see any reload happening in Firefox (v48.0.1)

**Comment by ramana-chavakula** [comment]
hey wesleycho,

can you check that again, my plnkr has not been updated with the latest changes

Thanks in advance

**Comment by wesleycho** [comment]
This use case is already covered in the known issues section of the documentation.

**Pull request closed without merging**
