### PR TITLE
fix(datepicker): don't fall back to parse using new Date(...)

### LINKED ISSUE #2508: Datepicker in Chrome parses in incorrect format
I configured the dateFormat for the German style: dd.MM.yyyy
Now when I enter "1.2." it gets parsed as 2nd of January. Expected is 1st of Febuary.

Another example that is pretty confusing for a user:
"1.02.2015" -> February 1st, 2015
"01.02.2015" -> January 2nd, 2015

I already browsed the code a bit and the cause is falling back to [new Date(viewValue)](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L512) which behaves very different across browsers.
Firefox: new Date("1.2.") -> undefined
Chrome: new Date("1.2.") -> Tue Jan 02 2001 00:00:00 GMT+0100 (CET)
Safari: new Date("1.2.") -> undefined

This can be reproduced using the [demo datepicker](http://angular-ui.github.io/bootstrap/).

I suggest to remove the fallback and to only rely on the DateParser that's part of bootstrap. Or at least to make the fallback optional.

### PR DESCRIPTION
**Pull request by cdietze**
Fixes #2508

### CODE REVIEW

**Comment by jmayday** [comment]
+1 (haven't seen this PR and prepared mine https://github.com/angular-ui/bootstrap/pull/3288). After some searching I found a lot of issues/PRs with some solutions. Would be nice to finally have one of them merged into master. 

Cheers.

**Comment by wesleycho** [comment]
This fails tests when rebased off of master.

**Comment by karianna** [comment]
@wesleycho Travis passes?

**Comment by wesleycho** [comment]
That is probably because it was valid when the PR was open.  It does not pass currently though.

**Comment by chrisirhc** [comment]
As I commented on #3294, this needs tests for validity of the date if it doesn't follow a specified format.

**Pull request closed without merging**
