### PR TITLE
chore: update package.json

### PR DESCRIPTION
**Pull request by wesleycho**
- Update package.json with more information
- Improve .npmignore slightly

### CODE REVIEW

**Comment by Foxandxss** [comment]
I have no idea what those package.json things does.

**Comment by wesleycho** [comment]
https://docs.npmjs.com/files/package.json#files
https://docs.npmjs.com/files/package.json#directories-lib

**Comment by Foxandxss** [comment]
I see, but I Got confusing with adding the files and then using npmignore too.

**Comment by wesleycho** [comment]
I added those files to npmignore so they wouldn't get accidentally published when we do move to use the main repository for npm releases.

**Comment by Foxandxss** [comment]
Yeah, well, in any case looks good, hope we don't break too much with this change.

**Pull request closed without merging**
