### PR TITLE
fix(modal): switch to $animate

### LINKED ISSUE #5298: Displaying the black square a few milliseconds in the "animation: false" in Modal
If you turn off the animation dialog box, at the moment, it appears completely black shade.

this problem can be clearly seen in the browser IE11, or on slower computers
screenshot_7

### PR DESCRIPTION
**Pull request by wesleycho**
- Change to adding backdrop with $animate.addClass due to $animateCss
  issues when animation is disabled

Plunker for fix [here](http://plnkr.co/edit/2QO7DC?p=preview).

This fixes #5298.

### CODE REVIEW

**Comment by deeg** [comment]
This LGTM

**Comment by sime** [comment]
Could this help #5314 ?

**Comment by wesleycho** [comment]
Possibly - if you'd like, feel free to investigate. It shouldn't take much work to verify if the usage of $animateCss is the case.

**Comment by sime** [comment]
Re: #5314 I tried and got completely lost. I haven't really used `$animate` and `$animateCss`.

**Pull request closed without merging**
