### PR TITLE
fix(tabs):  #2883 select gets called twice

### PR DESCRIPTION
**Pull request by caseyg1204**
Fix for https://github.com/angular-ui/bootstrap/issues/2883

### CODE REVIEW

**Comment by floriangosse** [comment]
+1

**Comment by karianna** [comment]
@caseyg1204 Is it possible to add/update the tests for this?

**Comment by wesleycho** [comment]
This smells like a hack - can you explain why it is being called twice?

**Comment by antonmaximus** [comment]
+1.  Happens to me on Bootstrap v3.3.4 & Angular v1.3.15.  I had to click twice for the non-active tab for it to be active.

**Pull request closed without merging**
