### PR TITLE
fix(typeahead): resolves property length of undefined error #2999

### PR DESCRIPTION
**Pull request by unkleara**
An error is thrown that matches.length is not defined. So we check if matches is truthy first.

### CODE REVIEW

**Comment by antoinepairet** [comment]
@unkleara thanks for the PR. Do you think you can write a test for this?

**Comment by unkleara** [comment]
Opps I changed deferred.resolve(['good', 'stuff']); to deferred.resolve(['good1', 'stuff']); to make sure I was logging a correct area. Want me to change that back?

Let me know any adjustments that need to be made. It can be tested other places but it makes most sense testing it within the promise since it's going through that function first.

**Comment by antoinepairet** [comment]
Yes please change it back.
Thanks for the test.
We will review it and merge it asap (I am on mobile now, so I cant review proprly)

**Comment by stmichael** [comment]
:+1: I'm having the same issue. Is there any progress on this issue? I'd really appreciate it, if it could be merged.

**Comment by johnnyreilly** [comment]
Is there any update on this?  Also causing me issues...

**Comment by wesleycho** [comment]
Is there a particular reason why it returns as undefined?

**Comment by chrisirhc** [comment]
There's no reason for that. I'm removing that expect call as I merge.

**Pull request closed without merging**
