### PR TITLE
fix(typeahead): Scroll only parent element, not apge

### LINKED ISSUE #5180: Using arrow keys to navigate typeahead response causes page to move when typeahead below the fold
https://plnkr.co/edit/vk7MZB7JXnE40U1AeU0z?p=preview

Go to the first example and type in a letter so some values show up. Then use the down arrow to try to scroll through those values. This moves the page so the highlighted value is at the very bottom of the page rather than keeping the page where it is and moving just the highlighted item.

This is also apparent on the ui-bootstrap homepage demo as the Plunk is just a copy of that example.

### PR DESCRIPTION
**Pull request by deeg**
Closes #5180 

[Plunker demonstrating fix](https://plnkr.co/edit/b3AWsVVul8hadUJwEoVC?p=preview)

Let me know if you want tests if this is a good solution. I can figure out a way to test it. FWIW does not look like this was being tested before.

### CODE REVIEW

**Comment by wesleycho** [comment]
I'm fine with this approach - @Foxandxss what is your thoughts?

**Comment by Foxandxss** [comment]
Fine for me, better if tested.

**Comment by deeg** [comment]
Sounds good, will add tests within an hour or so after I finish some work up.

Hope to make it into 1.0.1 if you don't mind waiting for an hour or two.

**Comment by Foxandxss** [comment]
That is fine by me.

**Comment by deeg** [comment]
Just added tests.

Thanks @wesleycho & @Foxandxss for the feedback and getting this into 1.0.1

**Comment by frfancha** [comment]
The behavior of the last typeahead in the plunker with fix is quite strange: sometimes it opens several pixels under the input instead of just below as usual, and the "candidate" row is not highlighted in blue.
See attached print screen (windows 7, firefox ESR 38.4.0)
typeahead_printscreen

**Comment by wesleycho** [comment]
That is actually a bug that has been existing for about 2-3 years on the demo page, but no fix yet.

**Comment by frfancha** [comment]
Ok but note that in the plunker without the fix (demo in 5180) I can't reproduce this last problem (at least not after 20 tries) (But I see the bug described in 5180 of course)

**Comment by deeg** [comment]
I am planning to fix another bug out there while making the behavior a bit better.

I will take a look at the issue you are describing @frfancha and see if I can't fix that also.

@wesleycho, do you know if there is a ticket for that one?

**Comment by wesleycho** [comment]
The positioning issue with the typeahead demo is the second mentioned in #1988

**Pull request closed without merging**
