### PR TITLE
refactor(modal,typeahead) Use $templateRequest

### PR DESCRIPTION
**Pull request by realityking**
One of the features in Angular 1.3 :)

### CODE REVIEW

**Comment by karianna** [comment]
@realityking Can you add some tests for this?

**Comment by pkozlowski-opensource** [comment]
@karianna I'm not sure new tests are needed for this, since it is internal refactoring that changes the code structure without altering external APIs / functionality.

+1 for @realityking change

**Comment by karianna** [comment]
@pkozlowski-opensource - Thanks! Have changed to needs:merging

**Comment by rvanbaalen** [comment]
Landed in e909b922a2ce09792a733652e5131e9a95b35e5b

**Pull request closed without merging**
