### PR TITLE
docs(tooltip-enable): Added description and sample

### PR DESCRIPTION
**Pull request by brunolellis**
Some explanation about https://github.com/angular-ui/bootstrap/issues/3372

### CODE REVIEW

**Comment by Psykar** [comment]
If you have no triggers set, this will actually enable/disable the default trigger of mouseover.
That is, if disabled, mouseover will not work.
If enabled, mouseover will work.

It *won't* just show the tooltip immediately.

**Comment by brunolellis** [comment]
@Psykar hm... I see.

`tooltip-enable`: Is it enabled? It will enable or disable the configured tooltip-trigger.

Is it better?

**Comment by Psykar** [comment]
Sounds better to me :)

**Comment by chrisirhc** [comment]
Made a few adjustments, thanks!

**Comment by chrisirhc** [comment]
Merged via 9a26b368038967ee049fc60e8490a2beebe4648a

**Pull request closed without merging**
