### PR TITLE
feat(datepicker): use $locale for starting day

### PR DESCRIPTION
**Pull request by wesleycho**
- Change to fallback to $locale.DATETIME_FORMATS.FIRSTDAYOFWEEK for
  first day column

This implements #4954.

### CODE REVIEW

**Comment by Foxandxss** [comment]
Does the previous forEach need startingDay as well? And I would like a docs update.

**Comment by wesleycho** [comment]
Forgot to remove that startingDay - good catch.

**Comment by Foxandxss** [comment]
Works for me now.

**Comment by wesleycho** [comment]
Updated PR to make this a non-breaking change - please re-review.

**Pull request closed without merging**
