### PR TITLE
Autofocus corrects the second time that the modal is open

### PR DESCRIPTION
**Pull request by ddomingues**
Autofocus corrects the second time that the modal is open. This fixes the issue #2802.
Example: http://plnkr.co/4sX9F3hObN0YmTU15m06

### CODE REVIEW

**Comment by haches** [comment]
+1

**Comment by karianna** [comment]
@ddomingues Are you able to add/alter the tests for this?

**Comment by ddomingues** [comment]
Ok @karianna . I'll do.

**Comment by haches** [comment]
@karianna thanks in advance. Would be awesome to have this PR merged.

**Comment by ddomingues** [comment]
@karianna Spec implemented.

**Comment by luisrudge** [comment]
Thoughts?

**Comment by wesleycho** [comment]
Landed as e5f5f75b370b6d4806da87bec575b7084e30c520, thanks for the work!

**Comment by luisrudge** [comment]
Is there a version with this already?

**Comment by wesleycho** [comment]
It will be released when 0.13 is released - we are hoping to have it out by latest in a month.  We are looking to address the main 1.3 compatibility issues currently for this release, as well as full integration with ngAnimate - both of these objectives are mostly complete.

**Comment by luisrudge** [comment]
Ok thanks!

Enviado pelo meu Windows Phone
________________________________

**Comment by luisrudge** [comment]
Is this released yet?

**Comment by karianna** [comment]
No

**Comment by luisrudge** [comment]
Thanks. Any ETA?

**Comment by rvanbaalen** [comment]
@luisrudge You can keep an eye on https://github.com/angular-ui/bootstrap/releases if you want to stay up to date with the release cycle. No need to post comments unrelated to the issue.

**Pull request closed without merging**
