### PR TITLE
feat(timepicker): add ngDisabled support

### PR DESCRIPTION
**Pull request by wesleycho**
- Adds support for `ng-disabled` on timepicker element for disabling all controls programmatically

This implements #2219

### CODE REVIEW

**Comment by Foxandxss** [comment]
Should this disable changes from model to view? Not sure if it does that already or if it makes sense.

**Comment by wesleycho** [comment]
It should not disable changes from model to view - Angular doesn't do it, and nor should we.

**Comment by Foxandxss** [comment]
Ok, good for me then.

**Comment by stefan--** [comment]
@wesleycho  enabling `ng-disabled` causes my form to be invalid although the model contains a valid date. I would expect it to be valid. Please have a look:

```
{
  "$error": {
    "dateDisabled": [
      {
        "$viewValue": "2016-03-24T09:30:00.000Z",
        "$modelValue": "2016-03-24T09:30:00.000Z",
        "$validators": {},
        "$asyncValidators": {},
        "$parsers": [],
        "$formatters": [],
        "$viewChangeListeners": [
          null
        ],
        "$untouched": true,
        "$touched": false,
        "$pristine": true,
        "$dirty": false,
        "$valid": false,
        "$invalid": true,
        "$error": {
          "dateDisabled": true
        },
        "$name": "",
        "$options": null
      }
    ]
  },
...
}
```

**Pull request closed without merging**
