### PR TITLE
Change uib-typeahead to typeahead

### PR DESCRIPTION
**Pull request by msemenistyi**

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@msemenistyi Why? This is not a valid change, as we've just introduced prefixes.

**Comment by msemenistyi** [comment]
@pkozlowski-opensource Here are options to the right of examples:
e66a339cf4bb35f8599929d936f2a5ce
What version were these prefixes introduced in? I was fighting to get it working for an hour looking at uib-typeahead examples

**Comment by Foxandxss** [comment]
0.14.0. If you need older docs, you can use the dropdown on the top of the page to change to the version you're currently working.

**Comment by msemenistyi** [comment]
@Foxandxss thanks

**Pull request closed without merging**
