### PR TITLE
fix(dateParser): added date validity check

### PR DESCRIPTION
**Pull request by pedroclayman**
added a date validity check
added zeros as default values for hours, minutes and seconds in addition to milliseconds

### CODE REVIEW

**Comment by rvanbaalen** [comment]
Can you add some tests for this?

**Comment by pedroclayman** [comment]
angular.isNaN does not exist as far as I know. Did you mean angular.isNumber ?

**Comment by pedroclayman** [comment]
angular.isNumber does not behave the way I need it to. neither does angular.isDate
```javascript
var date = new Date('foo'); // invalid date
console.log(date); // Date { invalid Date }
console.log(date.getTime()); // NaN
console.log(angular.isNumber(date.getTime())); // true
console.log(angular.isDate(date)); // true
console.log(isNaN(date.getTime())); // true - this is how I identify an invalid date
```
this solution is based on this: http://stackoverflow.com/questions/1353684/detecting-an-invalid-date-date-instance-in-javascript

Do you see a more suitable approach?

**Comment by rvanbaalen** [comment]
Ah well you're right. My bad. It was early in the morning :wink:

**Comment by menssen** [comment]
This is a duplicate of both #3731 AND #3708, both of which have tests.

**Comment by rvanbaalen** [comment]
Closing in favour of #3708. Thanks for reporting duplicate @menssen

**Pull request closed without merging**
