### PR TITLE
Fixed markdown in ngModal doc

### PR DESCRIPTION
**Pull request by posva**
Not much to say

### CODE REVIEW

**Comment by rvanbaalen** [comment]
Landed in 8297244aba1f00bc5ade125f2aaa4c024a09ab84

Sorry I didn't merge this in -- the hassle of merging and rebasing was more work than just make this quick ajustment.

**Comment by posva** [comment]
Doesn't really matter. Fixing the doc does :smile: 
But TBH I disagree, merging a PR is easier than doing the commit by yourself :confused:

**Comment by rvanbaalen** [comment]
@posva You obviously havent seen our PR-merging policy ;-)

https://github.com/angular-ui/bootstrap/wiki/Merging-a-Pull-Request

**Comment by posva** [comment]
haha Thanks! I did not. You are absolutely right, that is tedious :stuck_out_tongue:

**Comment by rvanbaalen** [comment]
Tedious for super small changes like this one, that is :wink: 
For all other PR handling, this way of merging PR's works perfectly.

**Pull request closed without merging**
