### PR TITLE
Update modal.js

### LINKED ISSUE #3134: Allow scope to windowTemplateUrl
Allow scope to windowTemplateUrl Now its not working. In windowTemplate cant add some buttons to close the modal and pass additional info like title or something.
there is an not working example. http://plnkr.co/edit/mysjPOXA68NiaXcqDKvA?p=preview
By edditing a modalWindow directive its posible to do all the stuf.
#3133

### PR DESCRIPTION
**Pull request by FDiskas**
Allow scope to windowTemplateUrl Now its not working. In windowTemplate cant add some buttons to close the modal and pass additional info like title or something.
there is an not working example. http://plnkr.co/edit/mysjPOXA68NiaXcqDKvA?p=preview
By edditing a modalWindow directive its posible to do all the stuf.
closes #3134

### CODE REVIEW

**Comment by jareddlc** [comment]
+1

**Comment by karianna** [comment]
@FDiskas Are you able to add some tests for this?

**Comment by FDiskas** [comment]
@karianna Sorry no

**Comment by wesleycho** [comment]
This looks like this would break the animation toggle of the `in` class with ng-class (see https://github.com/angular-ui/bootstrap/blob/master/template/modal/window.html ) - is there any reason why you can't add the buttons directly to the modal window through the transcluded template?

**Comment by wesleycho** [comment]
Ahh, I understand what the issue is now - I am going to close this in favor of #3390, as this should solve the problem in a non-breaking fashion.

**Comment by FDiskas** [comment]
Thanks

**Pull request closed without merging**
