### PR TITLE
feat(typeahead): implement 'select on blur' option.

### PR DESCRIPTION
**Pull request by DSI-Entreprises**
This PR adds an option 'select on blur' on typeahead. When enabled, this option selects the current highlighted value (in popup list) when the widget is losing focus. In short : clicking outside the widget is identical to hitting the 'tab' key.

By default, this option is disabled.

### CODE REVIEW

**Comment by karianna** [comment]
Needs tests and it currently fails the build...

**Comment by DSI-Entreprises** [comment]
Ok, I'm working on it... Thanks!

**Comment by DSI-Entreprises** [comment]
I have added two tests. Let me know if they are good enough. Thanks.

**Comment by wesleycho** [comment]
I like this - scheduling this to be merged for the next release (we've locked down 0.13.0 right now for Angular 1.3 compatibility).

Can you add documentation?

**Comment by DSI-Entreprises** [comment]
Thanks a lot !

**Pull request closed without merging**
