### PR TITLE
fix(popover): make it work with ngAnimate

### LINKED ISSUE #3375: ngAnimate breaks fade-in animation of popover
After including ngAnimate module to my application it breaks fade-in animation of popover.

Demo: http://plnkr.co/edit/3ECNoqBqfUcbwTq3MnVa

### PR DESCRIPTION
**Pull request by chrisirhc**
Fixes #3375

### CODE REVIEW

**Comment by wesleycho** [comment]
The previous value in the template was a binding - is this change ok as an immediately run class add?

Does this work when the user does not use ngAnimate?

**Comment by chrisirhc** [comment]
Yep it works, it didn't work as a binding because ngAnimate attempts to animate the animation class (`fade`) along with the `in` class at the same time. This PR ensures that the `fade` class is already there when the `in` class is added.

**Comment by chrisirhc** [comment]
Actually, good question, on further thought, I'll detect that if ngAnimate doesn't exist, skip adding the animation classes.

**Comment by wesleycho** [comment]
This good for merging then?

**Comment by chrisirhc** [comment]
Yep it is. Does fix the popover issues.

**Pull request closed without merging**
