### PR TITLE
fix(dropdown): Fix alignment for dropdown-append-to-body with .dropdown-menu-right when there's a vertical scrollbar

### LINKED ISSUE #4317: Right alignment is off for dropdown-append-to-body .dropdown-menu-right when there's a vertical scrollbar
This is related to issue #3820 
https://github.com/angular-ui/bootstrap/issues/3820

The right alignment is off when there's a scroll bar. 
Demo link: http://plnkr.co/edit/y6qOfyjM54YE8Ft1Vxj6?p=preview

Both dropdowns have dropdown-menu-right.
The first dropdown has the dropdown-append-to-body white the second doesn't.

If the height of the "TRIGGER SCROLL" div is changed to 200px, for example, then the alignment is fine in both dropdowns.

The alignment should be the same in both scenarios

Thanks

### PR DESCRIPTION
**Pull request by dolevd**
Fixes #4317 

This is going to be difficult to add tests for as the width of the scrollbar (that's used to calculate the alignment) is browser dependent.

[Plunk](http://plnkr.co/edit/bNk7aXxMyDRg0q6XK7sV?p=preview) with fix in place.

### CODE REVIEW

**Comment by wesleycho** [comment]
This LGTM - @RobJacobs is this the right fix?

**Comment by RobJacobs** [comment]
LGTM

**Comment by achenxp** [comment]
When there is no vertical scroll bar, the position of the dropdown is now incorrect.

**Comment by dolevd** [comment]
Can you please provide a plunkr that shows the problem?

**Comment by achenxp** [comment]
Here is the [Plunkr](http://plnkr.co/edit/YjTQj4Ct62ubErLXlz3Z?p=preview).

**Comment by dolevd** [comment]
Thanks. My code is missing a check for overflow.
I'll send another pull request to fix this.

**Comment by achenxp** [comment]
Thanks for the quick action!

**Comment by dolevd** [comment]
I have a fix in my fork: https://github.com/dolevd/bootstrap/commit/f838eb649ed59364fa7c19f4448e6e6ecae9f7f9

However, this might create a performance issue (since we need to calculate the styles of the append to element on every watch).
Any suggestions on how to proceed?

**Comment by dolevd** [comment]
I've opened another issue to handle this (#5942), since I don't think anyone is looking at the comments here anymore.

**Pull request closed without merging**
