### PR TITLE
fix for transitions break in Chrome 40+

### PR DESCRIPTION
**Pull request by warpdesign**
See bug report here: #3228

### CODE REVIEW

**Comment by karianna** [comment]
@warpdesign - Auto merge fails, please resolve merge conflicts and push again.

**Comment by warpdesign** [comment]
How can I do that ? (is it possible from GitHub ?)
I'm surprised there's a conflict seeing the very little changes there are: https://github.com/warpdesign/bootstrap/commit/dcbb4087063e856ca083d8dba6353133a41ba67b

**Comment by karianna** [comment]
You'll need to pull from angular-ui/bootstrap master and see what the conflicts are (you can also look at the Travis build failures.)

**Comment by warpdesign** [comment]
How, looking at Travis, it was actually a jshint error, I did another pull request which now passes Travis tests: https://github.com/angular-ui/bootstrap/pull/3241

Thank you.

**Pull request closed without merging**
