### PR TITLE
Update dropdown.js

### PR DESCRIPTION
**Pull request by matusszabo**
When using dropdown to show search suggestions, while hiding/showing dropdown menu and using key nav, it cause exception (cannot get property "focus" of undefined)

### CODE REVIEW

**Comment by icfantv** [comment]
@matusszabo, your build failed because of the linter and you have no tests for this case.  that said, our demo is working fine, which makes me wonder if you're dynamically setting the values in the dropdown and causing this issue.

Please paste a working plunker that shows the issue.

**Comment by matusszabo** [comment]
Hi @icfantv , yes,  only when loading options dynamically: https://plnkr.co/edit/WDqfQPJt5x52u3TDitFL?p=preview

**Comment by icfantv** [comment]
Ok, I don't know if this is a use case we want to support, although the alleged fix seems innocuous enough at first glance.  Need to ask the team.  @wesleycho @Foxandxss?

**Comment by wesleycho** [comment]
This needs a reproduction.

**Comment by wesleycho** [comment]
Closing due to this needing to go through issues with proper reproduction first.

**Comment by matusszabo** [comment]
@wesleycho, what kind of reproduction do you need, plunker is not good enough ?

**Pull request closed without merging**
