### PR TITLE
fix(tooltip): ensure tooltip custom CSS is imported with webpack

### PR DESCRIPTION
**Pull request by mattlewis92**

### CODE REVIEW

**Comment by wesleycho** [comment]
Does this play nice with Browserify?

**Comment by mattlewis92** [comment]
If you have the right plugin installed it should, it's how the carousel, typeahead etc already function i.e they already require css files

**Comment by wesleycho** [comment]
Looks like we already do this in the other components, this just got missed.

LGTM

**Comment by mattlewis92** [comment]
Awesome, thanks!

**Comment by RobJacobs** [comment]
@wesleycho @mattlewis92 Looks like this is missing for the position.css in the position index.js too. Popover index.js has a require on tooltip.js, is tooltip.css needed there as well?

**Comment by Foxandxss** [comment]
If you require an index.js, all the requires inside are loaded as well.

**Comment by wesleycho** [comment]
Position needs it still - not sure if we're missing it on any others.

**Pull request closed without merging**
