### PR TITLE
feat(modal): add option to disable animations

### PR DESCRIPTION
**Pull request by chrisirhc**
Add ability to disable animations. Built on top of #2724 .

### CODE REVIEW

**Comment by andrewboni** [comment]
+1, can we get this merged?

**Comment by karianna** [comment]
@chrisirhc are you able to update the PR - it can't be auto merged / cherry picked.

**Comment by chrisguerrero** [comment]
+1

Any word on this?

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support

**Comment by chrisirhc** [comment]
Will rebase it in a short while, after I rebase  #2724 .

**Comment by wesleycho** [comment]
Moved milestone to 0.13.0 - sounds like we can get this in for the next release.

**Comment by wesleycho** [comment]
How much work is left on this PR @chrisirhc ?

**Pull request merged**
