### PR TITLE
fix(datepicker): Don't parse the date twice

### LINKED ISSUE #3643: datepicker 0.13.0 does not allow model updates after a parse error for certain dates when ng-model-options updateOn: blur is used
Using 0.13.0 of datepicker with ng-model-options="{updateOn: 'blur'}"

When entering a date that causes a parse error (e.g. 'abc'), subsequently entering a 10-character 'mm/dd/yyyy' date (e.g. 01/01/2014) will not update the $modelValue.  

Entering an 8-character date (e.g. 1/1/2014) or selecting the datepicker in the calendar does update $modelValue.

[Plunkr](http://plnkr.co/edit/zY1DiPfEskLmNONddPJF?p=preview)

This seems related to [https://github.com/angular-ui/bootstrap/issues/3609], but I wasn't sure if it was the same issue.  As an aside, the $invalid flag isn't being set on parse errors.

Would be interested if anyone is aware of a workaround.

### LINKED ISSUE #3644: Datepicker has trouble with some dates
This might be related to #3617 and/or #3643.

JSBin: http://output.jsbin.com/pasiweruhe/2/

I have a date field set up with the German date format (`dd.MM.yyyy`). After clearing the field and entering a date where the day part is larger than 12, it will fail and the date will be `undefined`.

The issue seems to be, that the date parser has trouble creating a valid date input when the input is an invalid date input.

### PR DESCRIPTION
**Pull request by realityking**
Fixes #3644, #3617 

Potentially fixes #3643 as well, but I haven't tested that one yet.

Unit tests are missing, as I'm at a loss how to test these issues with karma. I'd appreciate some pointers in this regard. If it's fine to add protractor tests, I'd be happy to do so.

### CODE REVIEW

**Comment by kelvinatorr** [comment]
Works for me. Thanks!

**Comment by rvanbaalen** [comment]
Looks good and seems to be fixing some problems. Thanks for the PR! Will look into this soon to merge it.

**Comment by rvanbaalen** [comment]
@realityking Can you please add some tests for this?

**Comment by realityking** [comment]
@rvanbaalen Just to clarify, these tests would need protractor. Is that ok?

**Comment by rvanbaalen** [comment]
My bad. Now I see your comment about Karma tests. Was running an hour of slightly brainless PR and Issue triaging :wink:

**Comment by realityking** [comment]
No problem, but I still don't have an answer ;) Are protactor tests fine?

**Comment by morgenes** [comment]
+1

**Comment by wesleycho** [comment]
This change would have an effect on HTML5 date inputs I believe, since the $viewChangeListener is the only callback that gets fired that parses the date input.

Can you produce a Plunker with an example of this in action for that situation?

**Comment by Blackbaud-PatrickOFriel** [comment]
Any word on the status of this PR?

**Comment by realityking** [comment]
I haven't had time to set up protractor tests, so at least that's still open.

I'd be great if someone could create the test mentioned by @wesleycho as I'm pretty short on time right now.

**Comment by almeidap** [comment]
I can confirm that this fixes some parsing and validation issues (particularly #1289), specially when manually changing the date.

For those using Bower who would like a hotfix, you may fetch AngularUI from here (minified version not updated): https://github.com/almeidap/angular-ui-bootstrap

**Pull request closed without merging**
