### PR TITLE
fix(modal): body content shift

### LINKED ISSUE #2631: the background move a little when opening a modal.
when I click button to show a "modal", the background move a little then move back, which is not happened in bootstrap and uikit modal.

### PR DESCRIPTION
**Pull request by RobJacobs**
Implements TWBS body padding fix to keep content in an element with a container class from shifting when the body overflow is set to hidden with the modal-open class.

Fixes #2631

### CODE REVIEW

**Comment by deeg** [comment]
Thanks for doing this! We might want to add some tests for the new logic in position service?

**Comment by RobJacobs** [comment]
Tests are difficult when it comes to DOM interaction.  You will notice most of the tests in the position module actually mock the DOM aspects (see offset test where it returns a mocked clientRect).  I don't know if testing against mocked values really does anything for us?

**Comment by wesleycho** [comment]
We need to eventually modify the build system to run tests via SauceLabs/Browserstack and run positioning tests across browsers.

**Comment by wesleycho** [comment]
This LGTM

**Pull request closed without merging**
