### PR TITLE
Issue #3307 fix - DatePeeker weeks

### PR DESCRIPTION
**Pull request by yanivefraim**
Issue #3307 fix - DatePeeker weeks - wrong date sent to "getISO8601WeekNumber" method. 
Should be the last week's day, and not the first (otherwise on start of a new year it will send a date of one of last year's days, and will get end of last year's weeks)
For example: 
The fist week of January 2015 starts at Thursday. The date sent to "getISO8601WeekNumber" was of the first day of the week (28.12.2014), returning the weeks of last year's December!

- There was an issue in unit tests as well: Sep 2010 weeks are 35-40, not 34-39, see http://www.epochconverter.com/date-and-time/weeknumbers-by-year.php?year=2010

### CODE REVIEW

**Comment by rodrik** [comment]
Does not fix completely. In December still there are weeks 53 and 54. After W52 it should restart W1 again.

0zxouin

**Comment by yanivefraim** [comment]
@rodrik @karianna :
Hey, for some reason Datepicker stopped working for me. I tried different branch, forking again etc. Nothing is working for me. Any idea? does it work for you guys? (I want to fix this issue and cannot complete it)

**Comment by yanivefraim** [comment]
OK - fixed the number of weeks @ the end of the year (will end in week 52 and start over from week 1 again)

**Comment by yanivefraim** [comment]
Related: #2306, #3158, #3148

**Comment by chrisirhc** [comment]
Closing this in favor #2306 as it makes no assumption of `startingDay` whereas this fix always picks the 6th day in the row, which may be a Sunday and lead to a wrong week number. I think it's least surprising to show the week number for the Thursday of the row.

**Pull request closed without merging**
