### PR TITLE
Fix typeahead validity if model is set manually

### LINKED ISSUE #3318: typeahead invalid if model is set manually
I use typeahead for finding movies. If a searched movie (e.g., The Big Lebowski) is not in the list, I use a modal to insert this movie and to select the just inserted movie in the typeahead-input-field. Here simulated with "Set model". After this selection the input-field is marked as invalid.

The problem of invalidity occurs if you type some text in the input field and then click "Set model". If the input field is untouched or initially marked as valid (because the just searched movie "Matrix" was in the list) and you "Set model" afterwards, the form is valid too.

Please look at the described example in this plnkr:
http://plnkr.co/edit/EUOYKIZu6oizcEXTQ3UH?p=preview

### PR DESCRIPTION
**Pull request by andrenarchy**
With this commit, the validity of a typeahead model is set to true if the model is set manually and the typehead directive is set to be non-editable.

Fixes #3318.

Thx to @jengeb for investigating the issue with me in a nightly hacking session. :smiley:

### CODE REVIEW

**Comment by karianna** [comment]
Test(s) please :-)

**Comment by andrenarchy** [comment]
Shall I add a non-regression test with the (stripped-down) example that @jengeb provided?

**Comment by karianna** [comment]
Yes please.

**Comment by andrenarchy** [comment]
Test is added and runs smoothly on [travis](https://travis-ci.org/angular-ui/bootstrap/builds/51509536).

**Comment by karianna** [comment]
Thanks!

**Comment by andrenarchy** [comment]
Any updates?

**Comment by chrisirhc** [comment]
Looks good to me. Will merge soon.

**Comment by wesleycho** [comment]
Landed as b004443371d75bb61e9a17a00a58b485c1279aee, thanks!

**Pull request closed without merging**
