### PR TITLE
fix(modal): Promise resolution after close animation #3057

### PR DESCRIPTION
**Pull request by nauticalcoder**
This change attempts to fix Issue #3057
This change moves the result promise resolution to after the close animation is finished.

This is to solve the issue where the result promise is currently getting resolved before the animation completes.  If you display a message box in the promise handler, it is displaying before the modal closes.

### CODE REVIEW

**Comment by fiznool** [comment]
+1, is there any chance of this being merged in?

I'm currently just setting an arbitrary timeout to stop content inside my modal from changing while the animation runs, and it would be much better to have this fix.

**Comment by karianna** [comment]
@nauticalcoder Are you able to add some tests for this?

**Comment by nauticalcoder** [comment]
I will work on adding some tests for this.  It might be a day or two.

**Comment by SnackyPete** [comment]
It would be better if this fix was designed as a Promise, rather than a callback. :)

**Comment by wesleycho** [comment]
Thanks for the effort, but I believe this is now addressed by @chrisirhc's work on transitioning to using ngAnimate for the modal.

**Comment by wesleycho** [comment]
Hmm I closed this prematurely I believe, but this implementation is flawed - the problem is that it should be opt-in, and hidden behind a configuration option so as not to be a breaking change.

**Pull request closed without merging**
