### PR TITLE
update gulp build to better align with custom builds

### PR DESCRIPTION
**Pull request by leon**
the dist files should not contains the version since this breaks builds when a new version comes out.

The package.json is also updated to better align with npm

### CODE REVIEW

**Comment by mchlbrnd** [comment]
+1! When can we expect this to be merged?

**Comment by wesleycho** [comment]
@chrisirhc & @Foxandxss, what are your thoughts on this? I believe you two are the ones familiar with the release process.

This is a breaking change, but one that may be sensible to do since the file names should just be fixed.

**Comment by chrisirhc** [comment]
We need to rework the publishing process. Right now, the contents of the bootstrap-bower repository should be what's used for publishing to npm. That repository doesn't contain version numbers.

**Comment by Foxandxss** [comment]
I don't think this PR matches what we are doing with our releases. We are using an external repo and all the stuff we generate into /dist is merely internal only.

If you think there is an issue yet, please open an issue for proper discussion.

Thanks.

**Pull request closed without merging**
