### PR TITLE
Optional autofocus on typeahead selection

### PR DESCRIPTION
**Pull request by angi-**
There's an issue with typeahead: when you select an item from the list the input is autofocused. While this is desirable for some users, I clear the input value on focus leaving me with an empty input after selection. That's why I added a parameter that tells the typeahead not to autofocus after selection. This parameter is optional so it will not affect users that don't specify it.

This also adresses the issue #1903

### CODE REVIEW

**Comment by karianna** [comment]
Hi @angi- Are you able to add a test for this fix?

**Comment by angi-** [comment]
Done, I added tests for both cases: normal functionality should autofocus, specifying typeahead-autofocus="false" should not autofocus.

**Comment by wesleycho** [comment]
The history needs to be cleaned up here - there should be no merge commit, and it should be squashed into one.

**Comment by wesleycho** [comment]
Closing due to being superceded by #4212.

I apologize that this was not able to get in, but the history was an issue in this PR.

**Pull request closed without merging**
