### PR TITLE
Fix for: https://github.com/angular-ui/bootstrap/issues/3701

### PR DESCRIPTION
**Pull request by IRus**
Complete fix for #3701

### CODE REVIEW

**Comment by wesleycho** [comment]
This is a duplicate of #3759.

**Comment by IRus** [comment]
@wesleycho no. please take a look at src/datepicker/datepicker.js

**Comment by wesleycho** [comment]
It is almost a duplicate line-for-line - the one different change made that is already in other numerous open PRs is a breaking change that must be handled more carefully.

**Comment by IRus** [comment]
Okay, no problem

**Pull request closed without merging**
