### PR TITLE
xml and html5 templates compliance

### PR DESCRIPTION
**Pull request by tomaszkrym**
1. added 'data-' prefix to custom attributes
2. replaced '&', '<' with XML entities &amp; &lt;
3. added "" value to attributes without value

### CODE REVIEW

**Comment by k7sleeper** [comment]
HTML5 compliance is a must have for WCAG 2.0 compliance and that's a must have for the US market from december 2015.

**Comment by pkozlowski-opensource** [comment]
@k7sleeper could you please point to the section of WCAG 2.0 which states that "HTML5 compliance is a must"?

**Comment by k7sleeper** [comment]
It seems to me that I read section 4.1.1. of [WCAG 2.0 specification](http://www.w3.org/WAI/WCAG20/quickref/20150226/#ensure-compat-parses) not accurately enough :-( It only requires:

> **4.1.1 Parsing:** In content implemented using markup languages, elements have complete start and end tags, elements are nested according to their specifications, elements do not contain duplicate attributes, and any IDs are unique, except where the specifications allow these features. (Level A)
Note: Start and end tags that are missing a critical character in their formation, such as a closing angle bracket or a mismatched attribute value quotation mark are not complete.

which definitely does not say that one have to be fully HTML compliant.

[^](http://www.paciellogroup.com/blog/2012/02/wcag-2-0-parsing-error-bookmarklet/) gives a good explanation of WCAG conformance in relation to HTML conformance.

You helped me (and my team) much by simply asking that question.
Pls excuse any inconveniences that my statement my have caused.

**Comment by pkozlowski-opensource** [comment]
@k7sleeper the way I read it is that one should write "valid" HTML. It doesn't seem to say that it needs to be XHTML or HTML5.

**Comment by k7sleeper** [comment]
But which "specifications" does the requirement refer to? [This](https://html.spec.whatwg.org/multipage/syntax.html) for example?

**Pull request closed without merging**
