### PR TITLE
fix(tooltip): Tooltip misplaced near right side

### PR DESCRIPTION
**Pull request by dabos-GFI**
When the tooltip is near the right side of the first parent with relative positionning, the box size used to compute the tooltip position can change after the new location is set.
Then, it is required to reset the position (top: 0, left: 0) before computing the position.

Closes: #4195

### CODE REVIEW

**Comment by wesleycho** [comment]
This does not quite solve the problem, as can be seen [here](http://embed.plnkr.co/Lb1bm7WRd7R2bD5pvChh/preview) - note that in smaller viewports it does indeed work fine. It appears almost as if it only needs to be applied conditionally.

**Comment by dabos-GFI** [comment]
I am on it :)

**Comment by dabos-GFI** [comment]
Is there an issue associated with the problem?
My solution is to reset the width and height, and to fix the tooltip width and height width the one use to locate the tooltip.
It seems to work.

**Comment by wesleycho** [comment]
See my example with your changes I linked - it demonstrates a positioning problem that results.

**Comment by dabos-GFI** [comment]
Here is my new positionTooltip function version:

```js
var positionTooltip = function() {
              if (!tooltip) { return; }
              
              // Reset the positioning and box size for correct width and height values.
              tooltip.css({ top: 0, left: 0, width: 'auto', height: 'auto' });

              var ttBox = $position.position(tooltip);
              var ttCss = $position.positionElements(element, tooltip, ttScope.placement, appendToBody);
              ttCss.top += 'px';
              ttCss.left += 'px';
            
              ttCss.width = ttBox.width + 'px';
              ttCss.height = ttBox.height + 'px';

              // Now set the calculated positioning and size.
              tooltip.css(ttCss);
            };
```

For me it fixes your new problem too.

**Comment by icfantv** [comment]
@dabos-GFI we will also need tests for this.

**Comment by wesleycho** [comment]
I think for this sort of issue it's ok for there not to be tests.

**Comment by wesleycho** [comment]
This appears to work, as can be seen [here](http://plnkr.co/edit/du7NBdkdg9Mg9v0suXSp?p=preview) and [here](http://embed.plnkr.co/du7NBdkdg9Mg9v0suXSp/preview) - good work!

**Comment by dabos-GFI** [comment]
Edited example with last version of bootstrap-ui http://plnkr.co/edit/JU1jwv?p=preview

**Pull request closed without merging**
