### PR TITLE
chore(docs): Fix datepicker demo input type

### LINKED ISSUE #5115: Documentation error with datepicker examples on bootstrap directives page
On the angular bootstrap directives page, https://angular-ui.github.io/bootstrap/,  there is an error in the examples for the datepicker that involves the use of <input type="date" class="form-control" uib-datepicker-popup... instead of <input type="text" class="form-control" uib-datepicker-popup... with the result being that a different datepicker implementation is embedded within the bootstrap datepicker input.

The result of this can be seen by hovering over the associated datepicker input on the directives page, https://angular-ui.github.io/bootstrap/,  and the internal date picker control becoming visible and clickable.

### PR DESCRIPTION
**Pull request by deeg**
Closes #5115 

Let me know if you want me to remove the line in the readme.

### CODE REVIEW

**Comment by Foxandxss** [comment]
Under what cases a double datepicker appears?

**Comment by wesleycho** [comment]
@Foxandxss - `If using this directive on input type date, a native browser datepicker could also appear.`

**Comment by deeg** [comment]
@Foxandxss and @wesleycho, all good here, or do you want any changes made?

**Comment by Foxandxss** [comment]
Sounds good to me.

**Pull request closed without merging**
