### PR TITLE
fix for transitions break in Chrome 40+

### PR DESCRIPTION
**Pull request by warpdesign**
fix for transition break, see #3228

### CODE REVIEW

**Comment by karianna** [comment]
Thanks! PR just needs the tests updated :-).

**Comment by mhaligowski** [comment]
@karianna What tests need updating? Travis says it's ok?

**Comment by Aaike** [comment]
I also have no idea what tests would need updating.
But i just experienced this bug and applying this fixes it. please accept the PR.

**Comment by topikachu** [comment]
It seems new chrome made a change that only fires 'transitionend'  if both  'transitionend' and 'webkitTransitionEnd' are bound to dom. Please see my test at http://jsfiddle.net/kgtba8gv/4/

Some library for example ngAnimate uses "transitionend" so ui.bootstrap transitions has no chance to be called.

This PR really helps a lot of if some code need to work with ngAnimate.

**Comment by wesleycho** [comment]
This seems like a fragile fix - it is relying on the order the keys are in on the for var-in loop, which is not reliable.

**Comment by wesleycho** [comment]
I am closing this, as we have decided that we want to move to full ngAnimate support for 0.13, and we are going to be removing this service.  We are close to completion for usage of ngAnimate instead of $transition.

**Pull request closed without merging**
