### PR TITLE
refactor(typeahead): Add typeahead controller (WIP)

### PR DESCRIPTION
**Pull request by chrisirhc**
Tasks left:

- [x] Clean up duplicated code
- [ ] Add tests
- [ ] See if there are any other additions needed
- [ ] Finalize public API

Current known issues:

- Breaks defaults. Default min length is no longer there.

---

Allows other directives to extend functionality of controller.

Since typeahead-popup is a sibling that is right after the typeahead
input element, the controller can't be shared through the directive's
'require' option. As such, it's shared through the new child scope.

#### Example Typeahead Extension Directive

Here's an example that extends the typeahead directive to open on focus (#764):
http://plnkr.co/edit/UAWfTE
(Note that the example is based on my build which is on my demo branch https://github.com/chrisirhc/bootstrap-1/tree/demo/typeahead-extension , as typeahead needs fixes #886, #887 to get that functionality)

The directive is just:

    .directive('typeaheadOpenOnFocus', function () {
      return {
        require: ['typeahead', 'ngModel'],
        link: function (scope, element, attr, ctrls) {
          element.bind('focus', function () {
            ctrls[0].getMatchesAsync(ctrls[1].$viewValue);
            scope.$apply();
          });
        }
      };
    })

This follows ideas of `ngModel` and its `ngModelController` in AngularJS. The `typeaheadController` provides an API (just another object) that can be overridden, added, or called by other directives.

### CODE REVIEW

**Comment by uriklar** [comment]
+1

**Comment by wesleycho** [comment]
There is a lot of good work here, but this is likely very outdated - @chrisirhc any plans on finishing this up?  If not, we can open a separate issue with breaking up typeahead as a task.

**Comment by chrisirhc** [comment]
@wesleycho , let's leave this out since we need some work for Angular 1.3 anyway.
This didn't get in because I couldn't get to writing tests.

**Comment by chrisirhc** [comment]
I'm also hoping to move typeahead out of this repo since it's no longer core to bootstrap.

**Comment by Kikketer** [comment]
I really need this feature... are we simply delayed because we didn't have time to write a test?

**Comment by chrisirhc** [comment]
Yes. Feel free to open a pull request with tests to speed things along.

**Comment by Kikketer** [comment]
Thank you, but I found it was much quicker to find an alternative (AngularStrap in this case).

**Pull request closed without merging**
