### PR TITLE
fix(datepicker): fix validation for M! & d!

### LINKED ISSUE #5225: M!/d!/yyyy does not Validate in the Dateparser Example
http://angular-ui.github.io/bootstrap/

Format defined: M!/d!/yyyy

Failed
image

Expecting:
image

### PR DESCRIPTION
**Pull request by wesleycho**
- Fix display & validation for M! & d!

This fixes #5225 (tested on local docs).

### CODE REVIEW

**Comment by Foxandxss** [comment]
LGTM

**Comment by timonwong** [comment]
@Foxandxss @wesleycho 
I don't know whether or not this is a bug, it seems that it will drop the text after last (right-most) formatting token, for example:
```
dateParser.filter(date, 'yyyy -');
```
returns only "2016", dropped " -", is that intended?

and:

```
dateParser.filter(date, 'yyyy - MM -');
```
returns only "2016 - 02".

**Comment by wesleycho** [comment]
Hm, that sounds like a bug - can you open a new issue on that?

**Comment by timonwong** [comment]
@wesleycho 
Ok: #5387

**Pull request closed without merging**
