### PR TITLE
feature(datepicker): fix the issue #3748

### PR DESCRIPTION
**Pull request by sushantdhiman**
This update will add new directive which expose the `activeDate` for date picker. Thus able to watch current focused date.

Also fixes the issue [#3748](https://github.com/angular-ui/bootstrap/issues/3748)

### CODE REVIEW

**Comment by wesleycho** [comment]
The implementation looks incorrect here - the datepicker & datepicker popup directives should support an optional two way binding, where if present, it would update the data being bound to.

**Comment by sushantdhiman** [comment]
This directive only suppose to read the current focused date so user can take some action based on that date. Like fetching the data from api etc.

**Comment by wesleycho** [comment]
As built, there are problems with this implementation - this sort of wrapper is better provided as an external library, and not part of UI Bootstrap.

In addition, it contains hacks such as $timeout usage instead of instantiating it on proper timing, whereas a built in optional binding to the active date would allow the user to more easily consume it without mangling the HTML.

From an api standpoint, this is a poor implementation, and contains inefficient & fragile initialization logic.

**Comment by sushantdhiman** [comment]
Yeah I understand your point. I will update the implementation to expose the `activeDate` in `datepicker` rather than wrapping a component around it.

**Pull request closed without merging**
