### PR TITLE
Custom Karma configuration to only run tests for typeahead module

### PR DESCRIPTION
**Pull request by dmitriz**
Added:

// karma-custom-typeahead.conf.js

Custom Karma configuration to only run tests for typeahead module autoWatch is switched to `true`, so Karma will rerun all tests upon file changes
 
 run as:
   
     karma start karma-custom-typeahead.conf.js

Related to Issue https://github.com/angular-ui/bootstrap/issues/3542

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
I don't think we should be maintaining separate configs for each directive as proposed in 46f14d1
. This would be code / maintenance duplication while simpler solutions exists (changing globs in karma conf and / or using fdescribe / ddescribe).

**Comment by dmitriz** [comment]
Exactly my point, why I was asking for a better way:
 https://github.com/angular-ui/bootstrap/issues/3542#issuecomment-93247785

However, none of the other proposed ways seems to be better:

- Changing globs in karma is exactly what I did, however, doing it manually every single time,
after every single refresh, is impractical manual work. Further, there are subtleties (as per comments in the file), it took me time to find out and I don't want others to waste it again.

- Fdescribe leads to errors as I mention in the issue, can't be used with current `grunt watch`.

Imo, the only clean way would be have a task like `grunt watch:typeahead`, similar to `build:typeahead`.

Maybe I am missing something, then I'll be happy to learn.

**Comment by pkozlowski-opensource** [comment]
Then we should fix fdescribe / ddescribe issue instead.

**Comment by dmitriz** [comment]
The `ddescribe` warning/rejection is actually for good reason -- it safeguards you from forgetting to switch those `fdescribes` back before a pull request. Which is a good thing. 

But having to run through your code and __manually__ edit them, doesn't feel like a good thing.

Unless a convenient command like `grunt watch:typeahead` is enabled, having a dedicated clearly marked folder with custom Karma config files sounds like the next worse compromise I can think of.

**Comment by dmitriz** [comment]
Close for now as not pressing

**Pull request closed without merging**
