### PR TITLE
prevent typeahead-template-url working wrong

### PR DESCRIPTION
**Pull request by qpitlove**
prevent that dropdown has typeahead directive, typeahead-template-url is working wrong.

### CODE REVIEW

**Comment by wesleycho** [comment]
This needs more information - what is the problem, and why does this fix it? Reproduction via Plunker would be best.

Also the commit is from a different account - this needs to be verified that the person is ok with it being merged.

**Comment by wesleycho** [comment]
Ah, I see the original issue now (saw the PR first) - this seems related to the datepicker issue that is similar.

This needs investigation as to what is going on exactly here - in addition, the test needs to be fixed if this is to be merged.

**Comment by qpitlove** [comment]
Ok. I wrote issue before pr request.
https://github.com/angular-ui/bootstrap/issues/4239
Include reason and plunker example link

**Comment by qpitlove** [comment]
And my suggestion pr sample,  i don't care whether merge or not.

**Comment by qpitlove** [comment]
I'll close this pr.
Thanks.

**Pull request closed without merging**
