### PR TITLE
feat(modal): add pluggable resolve support

### PR DESCRIPTION
**Pull request by wesleycho**
- Adds support for pluggable resolvers, namely for supporting UI Router's resolve handling

Feature in action [here](http://plnkr.co/edit/F4jKuwwURnScqg4vvvCk?p=preview).

This implements #3405.

### CODE REVIEW

**Comment by icfantv** [comment]
This is pretty slick @wesleycho.  Nice work.

**Comment by Foxandxss** [comment]
I am good but the docs doesn't conform the design I have now. But not sure how to do it either.

**Comment by Foxandxss** [comment]
Also if post 1.0 is not going to have it, it is a bit "temporary"

**Comment by wesleycho** [comment]
Well, I am talking with the UI Router folks, it's trivial to re-add support & they're open to it, but it may require a documentation update to explain how to use it afterwards.

**Comment by Foxandxss** [comment]
That guy with sunglasses called @christopherthielen pss.

LGTM, it is a good addition indeed. I like our modal API like ng1 routes.

Let see what we achieve with ngbs.

**Comment by Foxandxss** [comment]
Oh wait, forgot about the doc thing.

**Comment by Foxandxss** [comment]
LGTM

**Comment by aphillipspq** [comment]
@wesleycho @icfantv  Was this discontinued from version 2.5.0?

**Pull request closed without merging**
