### PR TITLE
patch to allow hoverable tooltips/popovers

### PR DESCRIPTION
**Pull request by plong0**
adding `tooltip-hoverable=true` or `popover-hoverable=true` will enable the feature when hide trigger is mouseleave

### CODE REVIEW

**Comment by plong0** [comment]
adding `tooltip-hoverable=true` or `popover-hoverable=true` will enable the feature when triggers.hide is mouseleave

**Comment by RobJacobs** [comment]
There is already a mechanism in place to handle this, see the triggers section [here](http://angular-ui.github.io/bootstrap/#/tooltip).

**Comment by plong0** [comment]
Thanks, I've read over the tooltip triggers section, but could not see a trigger I could use that would allow the popover to stay open while I hover on the popover itself.
I did not see a specific answer in Issue #3515 either.

**Comment by RobJacobs** [comment]
I think you can accomplish this by creating your own trigger with the $tooltipProvider like so:

    $tooltipProvider.setTriggers({'mouseenter manual': 'manual' });

Then:

    <div tooltip-trigger="'mouseenter manual'" />

**Comment by wesleycho** [comment]
@plong0 can you try @RobJacobs solution and verify whether this is still an issue or not?

**Comment by RobJacobs** [comment]
@plong0 @wesleycho [Here](http://plnkr.co/edit/IlbdVm1aT70D4UB0NFA7?p=info) is a plunk that demonstrates the approach I suggested.  It would be nice if the [tooltip-prepTriggers](https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L327) method could be modified to not bind triggers set as 'none' or 'manual'

**Comment by plong0** [comment]
@RobJacobs thanks for the plunk... I understand better where you are going with using the existing tooltip-enable attribute.  In that plunk using the 'none' trigger, the tooltip is staying open even if I enter something in the input and move my mouse away.

The root of the problem is in detecting when the tooltip itself is hovered/unhovered, then triggering the tooltip to open/close.

**Comment by larserikfinholt** [comment]
What was the actual sln to this problem? @plong0 - did you manage to make a hoverable popover with the existing tooltip-enable attribute - in case how did you do that? Or was your PR accepted? (I could figure that out)

**Comment by plong0** [comment]
No I couldn't figure it out with the existing tooltip-enable attribute.  PR never got accepted either... I am just using my forked version for now.

**Comment by kentor** [comment]
great. another monkey patched solution

**Comment by RossRogers** [comment]
@RobJacobs,

You referenced a Plunk at this address http://plnkr.co/edit/IlbdVm1aT70D4UB0NFA7?p=info .  Unfortunately, that URL now redirects to a new, empty Plunkr.  Can you restore that Plunkr or recreate it, per chance?

**Comment by paulcamantigue-kaiser** [comment]
This saved me!  Had to adjust it for a very old version of angular-ui but it did the job :D

**Comment by asitpanda** [comment]
@RobJacobs , Given plunk url is redirecting to empty plunk.Could you give some link?

I am looking for this feature. Can any one here help me.

**Comment by icfantv** [comment]
@asitpanda, not sure it's fair to ask someone to recreate a plunk from 6 months ago and lord knows how many versions.  If you have a support-related question, please read our project documentation for how to receive support.

**Comment by asitpanda** [comment]
i requested a SO http://stackoverflow.com/questions/37108913/uib-tooltip-should-appear-while-mouse-over-on-it, i am using angular-bootstrap Version: 0.14.3, Can any one suggest something.

**Comment by odedkeren1** [comment]
I have solved it in a very cleaned way and thought to share it: .popover is being created not as a child of the uib-popover so the idea is to wrap uib-popover with a parent and to control show&hide on hovering the parent. .popover and uib-popover are children of this parent so just left to set popover-trigger=none and you have what you are wishing for.

I created a plunk example: https://plnkr.co/edit/6vzrrH1KUyQeLHDz1hWp?p=preview

**Comment by bmrinal** [comment]
@odedkeren1 this doesn't work with popover-append-to-body="true" option set !!

**Pull request closed without merging**
