### PR TITLE
fix(tabs docs): remove uib-tab's "active" setting

### PR DESCRIPTION
**Pull request by ivanvoznyakovsky**
after #5425 `uib-tab` documentation was not updated properly

### CODE REVIEW

**Comment by wesleycho** [comment]
LGTM - thanks for the catch.

**Comment by wesleycho** [comment]
Merged via f2004a9186e97cf40ac408e147bbcb508da072c0

**Comment by icfantv** [comment]
@wesleycho wait a second.  we added that as part of the bug fix for moving the active state to the tabset.  This should not have been merged.  We updated the comment correctly.  This should be put back in.

**Comment by RobJacobs** [comment]
Looks like the scope active variable is used internally to set the TWBS active class in the controller select function [here](https://github.com/angular-ui/bootstrap/blob/master/src/tabs/tabs.js#L14) and [here](https://github.com/angular-ui/bootstrap/blob/master/src/tabs/tabs.js#L20)  I don't think this should be documented as a publicly available attribute as I don't see how it could be used to report if the tab is active or not?

We should remove a reference to that in the docs [here](https://github.com/angular-ui/bootstrap/blob/master/src/tabs/docs/demo.html#L20)

**Comment by icfantv** [comment]
I should have said it was _modified_ as part of the tabset changes for the 1.2.2 release.  @RobJacobs, it's used for CSS.  Previously, it was used to actually set the tab's state to active, but that was moved to the `tabset` element.  I still think it's a valid attribute for documentation.

**Comment by RobJacobs** [comment]
@icfantv That's where I'm confused, I know the uibTab template uses uibTab scope.active variable to apply the TWBS active class, but how would a developer use that scope variable?  And if they can't, does it make sense to document it?

**Comment by RobJacobs** [comment]
Is that what the documentation blurb that was removed is describing?  To me, it looks like it was saying you could use the active attribute to do something with the css, which I don't believe is correct?

**Comment by icfantv** [comment]
My intention was to indicate that the attribute was for CSS purposes only - meaning that it was there for  CSS styling.

**Pull request closed without merging**
