### PR TITLE
feat(tabs): add CSS to css file

### PR DESCRIPTION
**Pull request by wesleycho**
- Add tab specific CSS to separate CSS file

### CODE REVIEW

**Comment by Foxandxss** [comment]
Can't be created that file inside the demo? not in the component root.

**Comment by wesleycho** [comment]
This mirrors what is done with the carousel: https://github.com/angular-ui/bootstrap/blob/master/src/carousel/carousel.css

**Comment by Foxandxss** [comment]
Ah, that explains why that file exists. Still, can't be both of those put inside docs?

**Comment by wesleycho** [comment]
Our build process actually bundles the CSS - try running `grunt` after checking this out to see.

This PR is not ready to merge though, I see this in the generated JS:
```js
angular.module('ui.bootstrap.carousel').run(function() {!angular.$$csp() && angular.element(document).find('head').prepend('<style type="text/css">.ng-animate.item:not(.left):not(.right){-webkit-transition:0s ease-in-out left;transition:0s ease-in-out left}</style>'); });
angular.module('ui.bootstrap.carousel').run(function() {!angular.$$csp() && angular.element(document).find('head').prepend('<style type="text/css">.uib-tab > div{position:relative;display:block;padding:10px 15px;outline:0;color:#337ab7;}.uib-tab > div:focus,.uib-tab > div:hover{background-color:#eee;color:#23527c;}.uib-tab.disabled > div{color:#777;}.uib-tab.disabled > div:focus,.uib-tab.disabled > div:hover{color:#777;cursor:not-allowed;background-color:transparent;}.nav-tabs > .uib-tab > div{margin-right:2px;line-height:1.42857143;border:1px solid transparent;border-radius:4px 4px 0 0;}.nav-tabs > .uib-tab > div:hover{border-color:#eee #eee #ddd;}.nav-tabs > .uib-tab.active > div,.nav-tabs > .uib-tab.active > div:focus,.nav-tabs > .uib-tab.active > div:hover{color:#555;cursor:default;background-color:#fff;border-color:#ddd #ddd transparent #ddd;}.nav-pills > .uib-tab > div{border-radius:4px;}.nav-pills > .uib-tab.active > div,.nav-pills > .uib-tab.active > div:focus,.nav-pills > .uib-tab.active > div:hover{color:#fff;background-color:#337ab7;}</style>'); });
```

**Comment by wesleycho** [comment]
Updated the PR - this should now be good.

**Pull request closed without merging**
