### PR TITLE
docs(timepicker): add templateUrl as config

### PR DESCRIPTION
**Pull request by Foxandxss**
@wesleycho I open this PR as a heads up on properly checking the PRs. The docs will fall behind really fast if we don't keep an eye.

### CODE REVIEW

**Comment by wesleycho** [comment]
Oops...that was a sloppy review on my part :( .

This LGTM.

**Comment by deeg** [comment]
Sorry about that, I forgot about the docs.

Are the extra line spaces a convention you guys have?

**Comment by wesleycho** [comment]
In this case, @Foxandxss did not add any extra lines - he stripped out extra whitespace in the lines.

Extra lines are mainly for readability though.

**Comment by Foxandxss** [comment]
Extra lines stuff was something my editor done by itself.

**Pull request closed without merging**
