### PR TITLE
chore: update with version support

### LINKED ISSUE #5436: Support Angular 1.5
Angular 1.5 is now stable, we should test against it. If it already works, we should indicate it in the readme.

### PR DESCRIPTION
**Pull request by wesleycho**
- Update to note support for 1.5
- Bump up the ngversion for Plunker

This closes #5436.

### CODE REVIEW

**Comment by Foxandxss** [comment]
There is something I wanted to do and this PR is perfect. Lock dependencies in package.json so we don't get caught into random update issues anymore.

**Comment by wesleycho** [comment]
What should I modify the package.json to? We're fairly loose with the dependency versioning there, since some users like to test the edges of Angular as it's released.

**Comment by Foxandxss** [comment]
what we put on the package.json  is irrelevant to those users because those are devDependencies.

I vote for hard locking it to "1.5.0" instead of "^1.x.x" that way travis won't use an updated angular when it gets out and freaking us out.

**Comment by wesleycho** [comment]
I'm still confused - where do we want to do this?

**Pull request closed without merging**
