### PR TITLE
update tooltip.js

### PR DESCRIPTION
**Pull request by DiHuang1986**
tooltip will be hidden before it is correct positioned. this change will prevent top left corner flicker...

### CODE REVIEW

**Comment by wesleycho** [comment]
Is the flicker based on what is currently in `master`?

**Comment by wesleycho** [comment]
Can you link a reproduction that demonstrates the flicker clearly on the most current version?

**Comment by DiHuang1986** [comment]
http://plnkr.co/edit/jnTT6PT9IMaBER7FenZN?p=preview

plunr example. put mouse on button, notice above

**Comment by wesleycho** [comment]
I like this solution - thanks a lot!

**Pull request closed without merging**
