### PR TITLE
fix(datepicker): default to current date

### LINKED ISSUE #5190: [Date picker] Calendar not rendering when initDate is undefined
Calendar is not rendering when `initDate` and model are `undefined`.

http://plnkr.co/edit/Dy9UvDb5z8vRt8phYypD?p=preview

### PR DESCRIPTION
**Pull request by wesleycho**
- When model is empty, default to current date

Fix in action [here](http://plnkr.co/edit/KDc90wvRgvBLSMLazdsd?p=preview).

This fixes #5190.

### CODE REVIEW

**Comment by Foxandxss** [comment]
That was weird code. LGTM.

**Comment by icfantv** [comment]
weird is one word to use, yes...

**Comment by wesleycho** [comment]
Looks like there are some unit tests that explicitly want this behavior - I need to do more research here.

**Comment by wesleycho** [comment]
PR now good for review - turns out it was a different line that was the culprit.

**Comment by icfantv** [comment]
LGTM with the understanding that these attributes will be deprecated in favor of the config object.

**Pull request merged**
