### PR TITLE
Candidate fix for #1812 - Modal + iOS virtual keyboard

### PR DESCRIPTION
**Pull request by stajs**
If the user-agent is iOS, then:

1. Add an extra class so that people can choose to opt in to the workaround by adding a style.
2. Adjust the heights for the modal and backdrop.
3. Ensure modal opens inside the viewport by adding top margin.

Style needed to complete the workaround:

```css
.modal-ios {
	position: absolute;
	overflow: visible
}
```

You could add the style inline, but probably better to just offer a hook for people to opt-in to.

Ref: #1812

### CODE REVIEW

**Comment by gluecksmelodie** [comment]
Awesome. Is there any chance to upvote this PR to be merged into master soon?

**Comment by karianna** [comment]
@stajs Needs tests and can't be merged

**Comment by stajs** [comment]
Well, it didn't have merge conflicts when I submitted it a year ago ;P

I don't have time in the short-term to investigate and resolve the conflicts, so if someone else feels like digging in that would be great.

@karianna What kind of tests are you looking for? I included some test cases in the referenced issue #1812. It's the kind of visual bug you'll have to run with an iOS device to test, so I included a plunk to reproduce a number of problems.

**Comment by karianna** [comment]
Fair point on the tests (I'll have to look into how we can automate those).

**Comment by wesleycho** [comment]
I do not believe that a user agent sniff is the correct approach in UI Bootstrap here.  What can be done is a user can do the user agent sniffing in their code, and pass in the appropriate strings to `windowClass` and `backdropClass` to add the conditional classes there.

Closing this as invalid.

**Pull request closed without merging**
