### PR TITLE
feat(tooltip): remove unnecessary `$digest`

### PR DESCRIPTION
**Pull request by wesleycho**
- Remove unnecessary call to `$digest`

Seems to work perfectly fine [here](http://plnkr.co/edit/BI4HEUxvq2Fkp2BRI6bT?p=preview).

### CODE REVIEW

**Comment by icfantv** [comment]
:+1:

**Comment by djeremh** [comment]
In your plunkr, the custom trigger tooltip doesn't work.

It seems refering to the commit https://github.com/angular-ui/bootstrap/commit/5726e3efae782dc400c39182943b6b33de57bb12.

**Comment by wesleycho** [comment]
@djeremh it does actually work - you have to scroll to the right though due to the window size allocated on Plunker.

**Comment by djeremh** [comment]
tricky, my bad on this.

**Comment by wesleycho** [comment]
Not a problem, I've had to do a double take multiple times over various issues too :) .

**Pull request closed without merging**
