### PR TITLE
Pull req ISSUE #3554 (Expose $modalstack openedWindows)

### PR DESCRIPTION
**Pull request by lc-nyovchev**

### CODE REVIEW

**Comment by karianna** [comment]
Can you add a test for this please.

**Comment by pkozlowski-opensource** [comment]
I would argue that we shouldn't merge this. As described in #3554 there is a way of doing things with a decorator, without extending the public API surface. Exposing internal data structure for not-so-common use-case (for which an elegant solutions with a decorator) will limit our ability to change internal data structures in the future.

**Comment by karianna** [comment]
@pkozlowski-opensource - Thanks for the review!  Closing as wontfix.

**Comment by lc-nyovchev** [comment]
Here is a plunkr that demonstrates the $delegate approach:

http://plnkr.co/edit/yKU2oObUaejuimMWxoDA?p=preview

**Pull request closed without merging**
