### PR TITLE
feat(tab): add select expressions

### PR DESCRIPTION
**Pull request by wesleycho**
- Add support for event and tab being available in select/deselect
  callbacks

This implements the third task of #4836.

### CODE REVIEW

**Comment by Foxandxss** [comment]
Tests? :P

**Comment by wesleycho** [comment]
I tried adding some tests, but it actually ended up locking up Karma - I think I might have to get clever about how to check the select/deselect arguments (`jasmine.any(Object)` caused issues, and I suspect a direct $scope comparison would too - might need to do a $scope.$id comparison).

**Comment by wesleycho** [comment]
I'm not sure this is testable - having circular reference issues since an object containing a $scope is passed into one of the arguments, jasmine seems to handle this poorly.

**Comment by wesleycho** [comment]
Removed $tab expression support, left as just $event support.

**Comment by icfantv** [comment]
Do we want a test for this?  If not, LGTM.

**Comment by wesleycho** [comment]
Updated with expectations!

**Comment by deeg** [comment]
LGTM

**Pull request closed without merging**
