### PR TITLE
Update modal.js to handle backdrop issue in bootstrap 3.3.1

### PR DESCRIPTION
**Pull request by maxisam**
To work with bootstrap 3.3.1. Ref #2970

### CODE REVIEW

**Comment by twwwt** [comment]
+1

**Comment by skmedia** [comment]
+1

**Comment by tony0918** [comment]
Any ETA? Thanks.

**Comment by karianna** [comment]
@maxisam Can you add a comment above the ```$(angular.element...)``` line stating the reason for it.  I think this PR is sane, but it'll allow more experienced folks than myself to see why it was added and enhance/revert as needed.

**Comment by pkozlowski-opensource** [comment]
I'm sorry but we can't merge this one as it assumes certain HTML structure of the backdrop template. We can't do this as people might want (and do) override default templates.

**Comment by maxisam** [comment]
@pkozlowski-opensource I thought about that too. But this project is for Bootstrap 3. It makes sense that we need to use modal-backdrop class in the template because it is in the original Bootstrap 3 and it is actually in the code not in the template.

var angularBackgroundDomEl = angular.element('<div modal-backdrop></div>');

 I do believe that we have different ways to resolve the issue, but I think it would require to change more than one line and one place.

**Comment by pkozlowski-opensource** [comment]
@maxisam we don't need to have one-liner fix. If a more generic solution requires more code so let it be. How about writing a dedicated directive that sets a height of a given element to `scrollHeight` and invoking this directive from a template?

**Comment by pkozlowski-opensource** [comment]
We shouldn't be afraid of creating small, focused directives - ones that are doing one thing well, are easy to test etc. The advantage of this approach is that people then can compose those smaller primitives.

**Comment by maxisam** [comment]
@pkozlowski-opensource  do you mean we create a directive invoked by the backdrop to set its height with the scrollHeight of modalwindow  ?

**Comment by kadamska** [comment]
@allaire your fix doesn't work for me when the modal is invoked after scrolling down... It works fine with no scroll offset.

**Comment by harsh55** [comment]
@kadamska : Just add this
.modal-backdrop{
    bottom: 0;
    position: fixed;
}
It will work for sure.  :+1:

**Comment by xtreemrage** [comment]
@kadamska : it works! :+1:

**Comment by betoecomp** [comment]
Using this approach also @harsh55 :thumbsup:

**Pull request closed without merging**
