### PR TITLE
feat(dateparser): add new format support

### PR DESCRIPTION
**Pull request by wesleycho**
- Adds `ww` support
- Adds `w` support
- Adds `G`, `GG`, `GGG` support
- Adds `GGGG` support

Should be noted, this almost finishes off #3418

### CODE REVIEW

**Comment by Foxandxss** [comment]
I can see week, but the other are a bit weird, not sure if they are going to be used, ever.

About #3418, I think it is implemented (we have `a` and `short`, `medium`....)

**Comment by wesleycho** [comment]
I'm not sure the era ones will ever be used, but it's nice to have the option, and it doesn't cost us much. It completes parity with the Angular dateFilter.

About `short`, `medium`, etc., how do we support that? I don't see anything obvious in the dateparser that allows for it.

**Comment by Foxandxss** [comment]
Using: https://github.com/angular-ui/bootstrap/blob/master/src/dateparser/dateparser.js#L219-L220

that will translate `short`, `mediumDate`, etc into a string that can be tokenized later.

**Comment by wesleycho** [comment]
Oh, so the issue will be finished then by this PR.

**Comment by Foxandxss** [comment]
Yes sir. Merge this

**Pull request closed without merging**
