### PR TITLE
fix(build): uib/ dir for ui.bootstrap.tpls dependency list

### PR DESCRIPTION
**Pull request by davious**
[Review on Reviewable](https://reviewable.io/reviews/angular-ui/bootstrap/4842)

### CODE REVIEW

**Comment by wesleycho** [comment]
The path is virtual - from the work in 342c576ea44e85f8406688109cdea12844341c3f, the virtual path has a uib prefix, to be in line with the rest of the project.

**Comment by davious** [comment]
when I do a build, the `dist/ui-bootstrap-tpls-1.0.0-SNAPSHOT.js`
line 9 is `angular.module("ui.bootstrap.tpls", ["template/accordion/accordion-group.html", ...]);`

all the templates looks like
`angular.module("uib/template/accordion/accordion-group.html", [])...`

so, when I use `ui-bootstrap-tpls-1.0.0-SNAPSHOT.js` I get this error 
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ui.bootstrap due to:
Error: [$injector:modulerr] Failed to instantiate module ui.bootstrap.tpls due to:
Error: [$injector:modulerr] Failed to instantiate module template/accordion/accordion-group.html due to:
Error: [$injector:nomod] Module 'template/accordion/accordion-group.html' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

**Comment by wesleycho** [comment]
I see - it would be better to maybe transform enquote to accept a function then & compose the functions, i.e. enquote(uibDir) instead of a double map.

**Comment by davious** [comment]
How about mapping with this?
```
function enquoteUibDir(str) {
  return enquote('uib/' + str);
}
```

**Comment by wesleycho** [comment]
That'd work too

**Comment by wesleycho** [comment]
Thanks for this - it was a good catch.

**Pull request closed without merging**
