### PR TITLE
fix(modal): keyboard=false should not stop trapping tab focus.

### PR DESCRIPTION
**Pull request by wawyed**
Fix for https://github.com/angular-ui/bootstrap/issues/4990

### CODE REVIEW

**Comment by wesleycho** [comment]
Can you add a test for this? Should be simple, just test when emitting the proper keypress event with `event.which` being 9, the esc key value, and testing whether it has been defaultPrevented.

**Comment by wawyed** [comment]
What would you like me to test? keyboard = false is already been tested by https://github.com/angular-ui/bootstrap/blob/master/src/modal/test/modal.spec.js#L747

**Comment by wesleycho** [comment]
Testing when hitting esc and making sure it isn't getting defaultPrevented normally is what I mean

**Comment by wawyed** [comment]
I'm a bit confused with what you mean. What does preventDefault have anything to do with my PR? The only test that I can think of adding would be that the trap focus on tab works correctly even when keyboard=false is used.

**Comment by wesleycho** [comment]
Ensuring that it isn't prevented is what I meant - the current behavior in `master` is that it will be prevented when tabbing (I got confused with the keycode heh).

**Comment by wawyed** [comment]
Made another PR with unit tests, https://github.com/angular-ui/bootstrap/pull/5010

**Pull request closed without merging**
