### PR TITLE
Added missing ng-change

### PR DESCRIPTION
**Pull request by hitautodestruct**
This documentation was missing the `ng-change` event.

### CODE REVIEW

**Comment by wesleycho** [comment]
I'm not seeing anything where ng-change is being used in the pagination directive.  I do not believe this is valid.

**Comment by chrisirhc** [comment]
Hm yea, I think `ng-change` can be used as a typical use case because `ng-model` supports `ng-change` on the same element.

Perhaps instead of mentioning it as a setting, we can mention that ng-change *can be used* on the pagination element (along with any ngModel formatter directive)?

**Comment by hitautodestruct** [comment]
@wesleycho @chrisirhc There seems to be no reference to access any way to get an event. I'm using the ng-change and can provide a demo if you want to see it working. The `ng-change` comes coupled with `ng-model`.

**Comment by wesleycho** [comment]
That sounds like a different issue, one worth filing an issue about.

**Comment by hitautodestruct** [comment]
It seems like there is a `selectPage(page.number)` method that is set as ng-click on every element. But again this is not documented.

**Comment by wesleycho** [comment]
Those sound like different issues - in that case, you should file an issue about them. @chrisirhc asked to make a modification to the wording for this PR, get that fixed up and we can merge this :) .

**Comment by hitautodestruct** [comment]
Done :)

**Comment by wesleycho** [comment]
Landed as df0bc00522c264963db9e086f758d42247d35070, thanks!

**Pull request closed without merging**
