### PR TITLE
fix(accordion): fix unexpected routing

### LINKED ISSUE #4533: ui-bootstrap-tpls + Accordion + FireFox + stopPropagation causes FireFox to reload page
I have a radio button in an accordion header to change how the data is presented. I have added an ngClick function($event, group) that runs `$event.stopPropagation` to prevent the accordion from closing and to allow the radio update the $scope variable.  This works as expected in Chrome, IE11, but causes FireFox to reload the page and start over, losing all the created data.

Please see plinker:  http://plnkr.co/edit/10mS8azqb2OkueNdGuus

If you watch the FireFox console.log you will see a reboot when the radio in the 2nd accordion header is selected.

Thanks

### PR DESCRIPTION
**Pull request by wesleycho**
- Change anchor tag to `div` to prevent anchor tag from triggering route change

BREAKING CHANGE: This causes the cursor style to be removed from the heading - implement CSS on the `accordion-toggle` class accordingly

This fixes #4533.

### CODE REVIEW

**Comment by Foxandxss** [comment]
Would a inline style on the div (for the cursor) be too much? In ng2 it is way better.

**Comment by wesleycho** [comment]
We could do it, but I think I rather it be captured in user CSS - less overhead in overriding there.

**Comment by Foxandxss** [comment]
that makes sense too. I am ok with both.

**Comment by charlierudolph** [comment]
Any time frame for the next release? Just spent a few hours trying to debug my app only to figure out it was related to this.

**Comment by wesleycho** [comment]
One can override the template locally for now to work around this.

As far as when it will be released, we're hoping for the end of the year - other than that, we can't say yet except to keep your eyes open.

**Pull request closed without merging**
