### PR TITLE
chore(Gruntfile): Add commonjs package manager support

### PR DESCRIPTION
**Pull request by oznu**
Adds support for commonjs/browserify when installed using NPM and allows injecting the module into an angular application like this:

````
var angular = require('angular');
angular.module('myApp', [
  require('angular-animate'),
  require('angular-ui-router'),
  require('angular-bootstrap'),
]);
````

### CODE REVIEW

**Comment by oznu** [comment]
https://github.com/angular-ui/bootstrap/issues/3021

**Comment by chrisirhc** [comment]
Moving this to Backlog as I don't think this is a priority for 0.13 . Also, curious as to whether this is the standard way to support Angular modules on CommonJS . I haven't done research/work on this myself. If anyone has any pointers, please post.

**Comment by chrisirhc** [comment]
I see https://github.com/angular/angular.js/pull/10732 now. Wasn't aware of it. Will look into this soon.

**Comment by oznu** [comment]
Closed this PR as I messed it up. New one created here at https://github.com/angular-ui/bootstrap/pull/3476 that takes into consideration the comments above.

**Pull request closed without merging**
