### PR TITLE
feat(loading): add "index-nocss.js" files

### PR DESCRIPTION
**Pull request by onlywei**
This allows SystemJS users to load the individual
modules without setting up CSS loading. Some build
processes with using SystemJS would rather have
a custom, separate CSS loading solution. This
commit allows that to happen.

### CODE REVIEW

**Comment by wesleycho** [comment]
This needs an exclusion added to https://github.com/angular-ui/bootstrap/blob/master/karma.conf.js#L29-L32

**Comment by onlywei** [comment]
Hmm, not really sure what this means:
```
Firefox 31.0.0 (Linux 0.0.0): Executed 1251 of 1251 SUCCESS (59.296 secs / 58.342 secs)
Running "build" task
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
/home/travis/build.sh: line 45:  3364 Aborted                 (core dumped) grunt
The command "grunt" exited with 134.
Done. Your build exited with 1.
```

**Comment by wesleycho** [comment]
Interesting failure - restarted the CI task

**Comment by wesleycho** [comment]
Hmm, maybe Travis is having issues - I'll hold off for a few days and come back to it.

FWIW, this LGTM, and will likely be merged without any need for further changes on your end.

**Comment by wesleycho** [comment]
I found out what was the error - it was a legitimate error where the Gruntfile also needed to be modified - I fixed it in `master` in two commits, shouldn't be an issue anymore.

**Pull request closed without merging**
