### PR TITLE
chore(transition): remove transition module

### PR DESCRIPTION
**Pull request by chrisirhc**
BREAKING CHANGE:
The `transition` module along with its `$transition` service are no longer
available. We're now using `$animate` service for animations and would
encourage users to do the same.

### CODE REVIEW

**Comment by wesleycho** [comment]
Should this be in the backlog or in 0.13.0? Given that $transition usage is gone, we might as well just delete it as a breaking change from 0.12 to 0.13.

**Comment by chrisirhc** [comment]
I was thinking of merging it next major release, say 0.14, as there might be users depending on it and it's not essential to drop it now. Just want to mark it as deprecated first.

**Comment by wesleycho** [comment]
Might be worth opening a PR marking it as deprecated in the comments for the service or when users consume the service via `$log`.

**Comment by chrisirhc** [comment]
Good idea, will do

**Comment by karianna** [comment]
@chrisirhc Weirdly this needs rebasing

**Comment by wesleycho** [comment]
Don't worry about this, the rebase would be easy when it comes time to do it.

**Comment by wesleycho** [comment]
I merged this in dfa4c97cb6ef7c83d88ffcfe7d31cdd851a58162, but looks like I forgot to just close this particular PR :(

**Pull request closed without merging**
