### PR TITLE
chore(travis): use latest node

### PR DESCRIPTION
**Pull request by Foxandxss**
Let's update travis like other libraries does :)

### CODE REVIEW

**Comment by wesleycho** [comment]
Just to be clear - this will run everything in iojs & node simultaneously?

**Comment by Foxandxss** [comment]
Yup, that would make travis test using a node 0.12 machine and a iojs machine.

**Comment by realityking** [comment]
Since ui-bootstrap doesn't produce any node modules, what is the advantage of running the tests in two different node environments?

This will double the build time, which might be undesireable.

**Comment by Foxandxss** [comment]
Yeah, that is right. I changed it just to bump node version. Even when we don't release node modules, we have lot of dev dependencies which could break with 0.10.

**Pull request closed without merging**
