### PR TITLE
fix(pager & pagination): prevent page reload in IE when anchor tag is disabled

### PR DESCRIPTION
**Pull request by roger2hk**
This fix is to resolve issue #6262.

### CODE REVIEW

**Comment by roger2hk** [comment]
@wesleycho according to your previous experience, would it be a problem to switch from `href` to `href="/"`?

**Comment by wesleycho** [comment]
Yes, that would break pretty much everyone's applications.

**Comment by roger2hk** [comment]
Could you please explain on what situation it would break the application?
It seems the `href` content has no effect on click.

Plunker that fixed the issue by using `href="/"`
http://plnkr.co/edit/6shfJl7yL5OcURpMSuo8?p=preview

Plunker showing pagination without ngRoute using `href="/"`
http://plnkr.co/edit/3PyB3cC6U2uSoQtImD2Q?p=preview

**Comment by wesleycho** [comment]
This breaks accessibility completely, as it is a false route. It also has SEO ramifications, and is susceptible to routing issues.

Closing this as invalid, this approach is a breaking change and has large impact negative ramifications.

**Pull request closed without merging**
