### PR TITLE
feat(datepicker): Add custom class to specific days via outside logic

### PR DESCRIPTION
**Pull request by Urigo**
Adding classes to specific dates with outside logic similar to date-disable.
Help with bringing more functionality to the picker that might prevent people from using fullcalendar.

https://github.com/angular-ui/bootstrap/issues/2616

### CODE REVIEW

**Comment by nemanjavuk** [comment]
+1

This would be great for next release!

**Comment by sandervanloock** [comment]
+1
Nice!

**Comment by arjunasuresh3** [comment]
+1

**Comment by wesleycho** [comment]
Landed as 0bcd30c4a6d65763e1c4d1b6820a4537a11e95ee, nice work!

**Comment by JGSimko** [comment]
Could someone please provide an example of this getting set up as a "datepicker-options" property? I've tried stepping through the code & my custom-class function gets called but the "ng-class" property is never added to the DOM resulting in no class being added.

**Pull request closed without merging**
