### PR TITLE
fix issue 4298: Parent context keeps a reference on destroyed childre…

### PR DESCRIPTION
**Pull request by yoann-antoviaque**
…n through closures

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
There are some style check failures, see: https://travis-ci.org/angular-ui/bootstrap/builds/77681435

**Comment by icfantv** [comment]
@yoann-antoviaque is there a way to add a functional test for your code changes?  if so, you'll need to do that as well.

**Comment by yoann-antoviaque** [comment]
Well the only way i spotted it was through heap dumps therefore i do not see any way to test it automatically...

Le 28 août 2015 5:31 PM, Adam Gordon <notifications@github.com> a écrit :

@yoann-antoviaque is there a way to add a functional test for your code changes? if so, you'll need to do that as well.

**Comment by wesleycho** [comment]
This is a very good catch - we should try to get this in as soon as possible.

Is it possible for you to write a test for this in the dropdown and typeahead components @yoann-antoviaque ?

**Comment by wesleycho** [comment]
Actually, not sure we can test for this - this is good as is.

**Pull request closed without merging**
