### PR TITLE
feat: add npm support in main repository

### PR DESCRIPTION
**Pull request by wesleycho**
- Add support for consuming the main repository via npm for releases

This addresses #4739.

### CODE REVIEW

**Comment by wesleycho** [comment]
This may still require a docs update - any recommendation for where to put that @Foxandxss ?

**Comment by wesleycho** [comment]
Hmm this is not quite right - need to define the `ui.bootstrap` module still.

**Comment by wesleycho** [comment]
My thoughts - we will want to document usage of this, as this is a major change.

There is no good way to bundle template support, but we can point people to some loaders such as https://github.com/teux/ng-cache-loader and https://github.com/WearyMonkey/ngtemplate-loader for Webpack and https://www.npmjs.com/package/browserify-ng-html2js for Browserify. We could perhaps provide a `template.js` helper file that does a bunch of requires for the templates, creates a `ui.bootstrap.tpls` module and export that, and import it into the `index.js` to maintain consistency with the previous complete bundle. This would require people are using Browserify or Webpack, and have the proper config setup for requiring HTML templates.

**Comment by Foxandxss** [comment]
Yeah, we have our hands a bit tied in regard of what we can provide. All we can do is to document the different options.

I will think in how can we make it as easy as possible.

**Comment by wesleycho** [comment]
Cleared by @Foxandxss

**Pull request closed without merging**
