### PR TITLE
chore(docs): fix popover and tooltip docs

### PR DESCRIPTION
**Pull request by icfantv**
* update popover and tooltip docs to indicate that the `uib-*-html` attribute
  does not get compiled
* addresses complaint in #4923

### CODE REVIEW

**Comment by deeg** [comment]
Not sure if specific people need to review it, but this LGTM.

**Comment by icfantv** [comment]
@deeg, yea we usually have another project dev give stuff a once over before we commit.

**Comment by deeg** [comment]
@icfantv, sounds good, thanks for the info.

**Comment by wesleycho** [comment]
LGTM

**Pull request closed without merging**
