### PR TITLE
Added a way to get the number of opened windows

### PR DESCRIPTION
**Pull request by martimarkov**
Using the `$uibModalStack.getOpenedWindowsNum()` we can get the number of opened windows/modals. This is great if we want to integrate with the angular-material design and edit the dropdown menu's z-index using the same formula as in the modal in angular-ui.

### CODE REVIEW

**Comment by wesleycho** [comment]
This needs a unit test.

**Comment by martimarkov** [comment]
@wesleycho it only exposes a variable. why would that need any kind of unit testing. Surely it should have been done on the variable itself beforehand.

**Comment by RobJacobs** [comment]
I would prefer this be called openedCount

**Comment by wesleycho** [comment]
Any method exposed publicly needs a unit test as a guarantee the API behaves as expected. Without one, this will be rejected.

**Comment by wesleycho** [comment]
Going to close this due to non-response - feel free to open a new PR with the appropriate test

**Pull request closed without merging**
