### PR TITLE
Fixing opened issue

### PR DESCRIPTION
**Pull request by Theo-**
See https://github.com/angular-ui/bootstrap/issues/5899 for more details

### CODE REVIEW

**Comment by wesleycho** [comment]
This seems wrong - we already have logic for handling selection on active change. See [here](https://github.com/angular-ui/bootstrap/blob/master/src/tabs/tabs.js#L79-L83) - if something is wrong, we should fix whatever is wrong here.

**Comment by Theo-** [comment]
The code you linked is about listening to the variable that points to the index of the active tab. But this variable is not set properly. There is no way of modifying the active tab just by modifying the data structure containing that the active attribute points to.

**Comment by wesleycho** [comment]
There's a two-way binding defined [here](https://github.com/angular-ui/bootstrap/blob/master/src/tabs/tabs.js#L104-L107). This should work, and there are tests against this.

If it's broken, the broken piece should be fixed, not adding another watcher that isn't properly gc'd on $scope destruction.

**Comment by Theo-** [comment]
See the plunker I provided in the bug description:
http://plnkr.co/edit/HY6UaOSTsW7YwEvTDlFm?p=preview

This two data binding is obviously not working. However I am not an angular pro, so I'll leave this to your judgment.

**Comment by icfantv** [comment]
@Theo- the broken tests aside, please address my question in your issue report.

**Pull request closed without merging**
