### PR TITLE
feat(datepicker): implement auto position

### PR DESCRIPTION
**Pull request by RobJacobs**
Added popup-placement attribute that implements the auto position
feature that exists in the tooltip directive.  Accepts the same
placement options as the tooltip.

This [plunk](http://plnkr.co/edit/aXDt2IIE0J91JetH6iU9?p=preview) demos the feature.

I haven't added test for this as I'm not sure on what the best approach is for finding an elements position in a test and would like some guidance on that.  The 2 minor changes in the readme.md is a result of my editor trimming trailing whitespace.

If this approach is acceptable, I plan on doing the same thing to the typeahead directive.

### CODE REVIEW

**Comment by icfantv** [comment]
Would it make sense to address #5414 with this commit as well?  That way you can work out the kinks before moving to typeahead and dropdown?

Linking in #4762 for tracking purposes.

**Comment by Foxandxss** [comment]
Sounds good to me.

**Comment by wesleycho** [comment]
This LGTM too

**Comment by wesleycho** [comment]
Hm, I guess I forgot about the test part - how much testing does this need? We could perhaps test given certain CSS scenarios with regards to maybe display: block, position: relative/absolute, and floats.

Tooltip/popover would need them too.

**Comment by RobJacobs** [comment]
@wesleycho I'm working on it still, will create another PR in the near future.

**Pull request closed without merging**
