### PR TITLE
feat(typeahead): access to $item in typeahead-input-formatter and item resolver

### PR DESCRIPTION
**Pull request by miiihi**
This solves problems with input formatting and initialization. IMO it fixes https://github.com/angular-ui/bootstrap/issues/981, https://github.com/angular-ui/bootstrap/issues/274... 

In short, we add access to $item in formatter, if we have an item, if we don't (ie. on initialization and programaticaly setting value), we use callback for item resolving and rerun formatters, when callback returns.

### CODE REVIEW

**Comment by smurugavel** [comment]
Hello..
This is a great accomplishment in typeahead for complex data needs. $item suits me well. I was wondering if there are plans to port this code, so it is compatible with angular ui 0.13.3 and angular 1.4?

thanks
Murugavel

**Comment by pkozlowski-opensource** [comment]
Well, this "great accomplishment" doesn't merge cleanly any more and doesn't have associated tests. There is no way we can merge such a substantial patch without associated unit tests.

@miiihi see my comment above - if you are still interested in getting this in, please rebase on top of current master, add tests and submit a new PR. Thnx!

**Comment by smurugavel** [comment]
I see that as an attempt made and being successful. I agree that this doesn't merge well on latest code but it worked in ui-bootstrap-tpls-0.13.0.js. Yes, I understand the latest version is 0.13.3

**Comment by pkozlowski-opensource** [comment]
@smurugavel it is more about lack of unit tests. Once again, we need to have tests to prove that the code does what it claims and avoid regressions in the future.

**Comment by miiihi** [comment]
Well, I'm interested in getting this merged, since we use this in production - but as there was zero response to my pull request I didn't pursue this any further...

Will rebase and prepare unit tests asap.

**Pull request closed without merging**
