### PR TITLE
Make all versions the same level in the ChangeLog.

### PR DESCRIPTION
**Pull request by svetlyak40wt**
Please, make all versions the same level headers, because otherwise it seems that 1.0.1, 1.0.2 and 1.0.3 are subsections of 1.1.0.
And this is breaks automatic changelog parser at https://allmychanges.com/p/web/angular%20bootstrap/

### CODE REVIEW

**Comment by icfantv** [comment]
Thanks for taking the time to do this.  Unfortunately, we switched changelog generators (or a version changed somewhere) and this got missed.

That said, you should rely on the format of the last few entries as the official format or this is going to break again with the next release.  We'll need to look at the changelog generator to see if/how we can control this.

Finally, I would be VERY wary of third party changelog parsers for exactly this reason - you will always (ok, usually always) get the correct information from our official copy of the changelog and we cannot guarantee the information hosted by any other site.

**Comment by wesleycho** [comment]
This needs to make the appropriate changes to https://github.com/angular-ui/bootstrap/blob/master/misc/changelog.tpl.md as well.

**Comment by icfantv** [comment]
Oh cool. So it is a template.  That makes things easier.

**Comment by svetlyak40wt** [comment]
Should I reformat changelog to make all versions level 1 header and sections in description, level 2?
As I see, template uses these levels.

**Comment by svetlyak40wt** [comment]
Ok, I've fixed formatting according to template.

**Comment by icfantv** [comment]
This LGTM, but given the sheer number of changes I'd like another set of eyes.

**Comment by wesleycho** [comment]
LGTM

**Comment by svetlyak40wt** [comment]
Thank you, guys!

**Pull request closed without merging**
