### PR TITLE
feat(dropdown): use .value() for uibDropdownConfig

### PR DESCRIPTION
**Pull request by onlywei**
This allows people to use .decorator() to customize this object.

#6004.

### CODE REVIEW

**Comment by onlywei** [comment]
#6004

**Comment by wesleycho** [comment]
Note that the issue shouldn't be closed, as this should be done for every component.

**Comment by wesleycho** [comment]
Unfortunately, I'm going to have to revert this since it turns out this is a breaking change (the constant becomes no longer injectable inside a config function).

**Comment by onlywei** [comment]
@wesleycho why is that a breaking change? I grepped through the `src/` directory and found that it was not being injected into any config functions.

**Comment by pkozlowski-opensource** [comment]
> I grepped through the src/ directory and found that it was not being injected into any config functions.

But users of this lib might be doing so.

**Comment by onlywei** [comment]
I see. In that case, going forward, will the below be the recommended way for users of the lib to configure the dropdown library?
```
import angular from 'angular';
import uibDropdown from 'angular-ui-bootstrap/src/dropdown';

angular.module('MyApp', [uibDropdown])
  .config(function (uibDropdownConfig) {
    uibDropdownConfig.openClass = 'is-open';
  });
```

?

**Pull request closed without merging**
