### PR TITLE
feat(dropdown): Make dropdowns close on touchstart event

### PR DESCRIPTION
**Pull request by redmagic**

### CODE REVIEW

**Comment by chrisirhc** [comment]
Linking previous PR of #3532 for reference.

:+1: This should fix #3242 . Thanks! Next time do take note please refer to the issue that this is trying to fix. It makes things easier to track for maintainers.

**Comment by redmagic** [comment]
I have a dropdown with nested anchor in it and they do receive the clicks/touches. However, this was only after I added ngTouch to my project, so there is a depency on some sort of fastclick mechanism. The most bulletproof solution would be to check in the listener if the event originated from within the menu and ignore it if that's the case. I'll try to look into it some more, and will keep an eye on the issues you mentioned.

**Comment by dmitriz** [comment]
Your forked branch `master`
https://github.com/redmagic/bootstrap/tree/master

 is 
 1 commit ahead, 7 commits behind angular-ui:master

As the result your diff

https://github.com/redmagic/bootstrap/commit/d2a1a6896316b874515a7d993008326813548dbe

does not show correctly your change - `hasClass('open')` instead of the most recent

https://github.com/angular-ui/bootstrap/blob/master/src/dropdown/test/dropdown.spec.js#L62

You may want to correct it with `rebase` (and possibly resolve conflicts) so it would merge, see below.

----

I usually run 

      git pull --rebase upstream master

where my remote settings are:

<pre>
git remote -v
origin	https://github.com/dmitriz/bootstrap.git (fetch)
origin	https://github.com/dmitriz/bootstrap.git (push)
upstream	https://github.com/angular-ui/bootstrap (fetch)
upstream	https://github.com/angular-ui/bootstrap (push)
</pre>

So the above `pull` command always pulls the most recent changes and puts my new history on top of that.

Sometimes this leads to *rebase conflicts*, which is actually a good thing, because it is much better for me to resolve them locally and then submit for public review.

After the rebase I push my local **PR candidate branch** to my fork with 

    git push -u my-new-feature origin my-new-feature

after which I can easily submit PR from there.

**Comment by rvanbaalen** [comment]
@dmitriz Please keep your responses ontopic. No need to discuss your git techniques here.

**Comment by chrisirhc** [comment]
Closing this due to discussion in #3257 and #3242.

**Comment by dmitriz** [comment]
@rvanbaalen I've thought it would help the author, as he didn't seem to `rebase`, and the information is scattered, so it might save him time. Just tried to be helpful. Isn't this concise all-in-one-page explanation-solution not helpful to the author?

**Pull request closed without merging**
