### PR TITLE
feat(modal): Adds `defaultContainer` to `$modalProvider`

### PR DESCRIPTION
**Pull request by Lalem001**
Includes basic tests, with adjustments to `toHaveModalsOpen` and `toHaveBackdrop`.

Fixes: #2688

### CODE REVIEW

**Comment by wesleycho** [comment]
Can you update this with current master?

**Comment by Lalem001** [comment]
I will close this one, and make a new PR with latest master. Will link to new PR here when its ready.

**Comment by Lalem001** [comment]
@wesleycho Regarding the change suggested above with separate containers for modal and backdrop, how would you prefer it be done?

Like:
```js
$modalProvider.modalContainer = body;
$modalProvider.backdropContainer = body;
```

Or:
```js
$modalProvider.defaultContainers = {
    modal: body,
    backdrop: body
}
```

Other?

**Comment by chrisirhc** [comment]
Fyi @Lalem001 , you can force push to the branch that this PR is based on to update it, so you don't need to create a new PR.

**Pull request closed without merging**
