### PR TITLE
refactor(dropdown): register module at EOF. Update comments.

### PR DESCRIPTION
**Pull request by alettieri**
I used this directive in one of our internal projects. I needed to update the structure (to match our code base) and commenting for documentation purposes. Thought this might be helpful for the project as well?

### CODE REVIEW

**Comment by karianna** [comment]
Needs tests at the least :-)

**Comment by alettieri** [comment]
@karianna these changes shouldn't be breaking the previous test cases. It's mostly just changing the code structure and adding comments. I ran these against the current test cases and they still pass. Nothing new was introduced.

**Comment by wesleycho** [comment]
I'm closing this as invalid, this does not match the structure of the rest of the project, making it more difficult to follow for anyone contributing or perusing the source code.

**Comment by alettieri** [comment]
@wesleycho fair point on structure. Where is it publishing methods on window?

**Comment by wesleycho** [comment]
The compiled version is not wrapped in an IIFE, so any globals would be globals on window.

**Comment by alettieri** [comment]
@wesleycho ah, yes, I see what you men. I didn't consider that the compiled version wouldn't be wrapped in an IIFE. Anyways, thanks for clarifying and addressing the pull request. Will keep the style/structure in mind if I ever have something else to contribute.

**Pull request closed without merging**
