### PR TITLE
feat(datepicker): add helpers for styling

### PR DESCRIPTION
**Pull request by wesleycho**
- Add helper variables available for custom templates to hook into for styling

### CODE REVIEW

**Comment by deeg** [comment]
Did we want any tests for this?

**Comment by deeg** [comment]
This LGTM

**Comment by wesleycho** [comment]
I thought about it, but we don't even have tests for current excepting that it adds the btn-info class appropriately - I made no changes to that logic though.

**Comment by icfantv** [comment]
I'm ok with this.

**Pull request closed without merging**
