### PR TITLE
fix(datepicker-popup) init-date attribute

### PR DESCRIPTION
**Pull request by thomaswinckell**
Fix of the init-date attribute for the datepicker-popup. The init-date attribute, when set in a datepicker-popup element, is now added to the datepicker element and in the datepicker-popup scope, so the datepicker element can retrieve the attribute value. See issue #2331.

### CODE REVIEW

**Comment by dciccale** [comment]
LGTM

**Comment by rvanbaalen** [comment]
Could you add a test for this case as well? Ill be pulling this in shortly then.

**Comment by karianna** [comment]
@thomaswinckell as @rvanbaalen mentions, can you add a test for this?

**Comment by wesleycho** [comment]
Landed as c5b63ded0aebd7ae80f238bd0a33f1d9c0746dba with tests.  Thanks!

**Pull request closed without merging**
