### PR TITLE
feat(tab): enable string as index

### PR DESCRIPTION
**Pull request by norami**
Enable string index for tab.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
We need a unit tests before it can be considered for merging

**Comment by RobJacobs** [comment]
This is more involved and will need additional changes.  See discussion in PR #5713, we should re-open that one.

**Comment by sandeepthomas** [comment]
Waiting for this to be implemented. In the meantime, is there any workaround to add active class to the changed tab (ul li) on using string as index?

**Comment by icfantv** [comment]
@deeg @RobJacobs what is the status of #5713 you guys were working on?  Is this something you guys can fix?  People have been asking for this and we need to get it implemented.  Thanks.

**Pull request closed without merging**
