### PR TITLE
chore(build): update dependencies

### PR DESCRIPTION
**Pull request by wesleycho**
- Change the angular version to 1.4.3 for docs
- Change the Bootstrap version to 3.3.5 for docs

### CODE REVIEW

**Comment by Foxandxss** [comment]
We sure we want to bump the bootstrap version?

**Comment by wesleycho** [comment]
I checked every component when I was checking for angular 1.4 compatibility, didn't see any issues - it would also allow us to fix them quicker if they do happen to come up.

**Comment by Foxandxss** [comment]
Oh, that is good to hear. The LGTM

**Comment by wesleycho** [comment]
Hmm looking at the 0.14 milestone, perhaps it would be wise to reset that - there are a few minor issues around.

**Pull request closed without merging**
