### PR TITLE
feat: added build task for separated components

### PR DESCRIPTION
**Pull request by m99coder**
Maybe this small enhancement is useful for you in case somebody (as me) needs separated compiled components.

### CODE REVIEW

**Comment by wesleycho** [comment]
I'm confused - how is this significantly different from the current task that compiles to `dist`?

**Comment by m99coder** [comment]
Current `grunt dist` compiles together all components in one file and creates a second one for the templates beside. We need artifacts which are separated into their components to only include `modal` for instance. Some of your directives create a naming conflict with our own library. It’s a little bit more flexible if you ask me.

**Comment by wesleycho** [comment]
Maybe a subfolder inside `dist` such as `dist/components` might be more desirable then?

**Comment by m99coder** [comment]
That would be nice. Feel free to decide where it should reside best. Finally we created a corresponding bower-compatible repository too from where these artifacts can be included in our applications. So maybe you could deploy the whole `dist` folder contents to `https://github.com/angular-ui/bootstrap-bower`?

**Comment by wesleycho** [comment]
Closing as we decided instead to move to more robust npm support so that one can load/require the scripts one needs and use Browserify/Webpack plugins to load the templates into JS.

**Pull request closed without merging**
