### PR TITLE
chore(tabs): add nested forms example

### PR DESCRIPTION
**Pull request by icfantv**

### CODE REVIEW

**Comment by wesleycho** [comment]
Oh master of docs @Foxandxss , I summon thee to review this PR!

**Comment by Foxandxss** [comment]
I am going to let it sit a bit until I reach tabs.

**Comment by wesleycho** [comment]
Could review/merge it and then refactor when you get to it - having a good reference point with code already done could reduce the work necessary.

**Comment by Foxandxss** [comment]
Avoid making generic classes, check the typeahead to see how we write css classes for demos.

**Comment by icfantv** [comment]
That's fair.  Fixed it.

**Comment by wesleycho** [comment]
Thoughts on this @Foxandxss ? This looks good to me now.

**Comment by Foxandxss** [comment]
Good to me.

**Pull request closed without merging**
