### PR TITLE
Extending typeahead-popup functionality

### PR DESCRIPTION
**Pull request by shank8**
Today, the `typeahead-popup-template-url` implementation only works if the array you wish to display in your new template is processed by a single `ng-repeat` directive. However, in the case where you may want to split up your initial array into "filtered" subsets and `ng-repeat` across all subsets, this implementation fails.

The reason it fails is because currently, the logic uses `$index` to track the array and therefore uses `$index` to "find" the selected item from the original list.

Let me explain with an example:

In my case, I have a list of 10 book objects. Lets say each book has a UID to identify it from any other book. Lets also say it has a `genre` property which could be 1 of 2 values ("fiction" or "non-fiction").  Then in my `typeahead-template-url` I set up the template to group each genre into their own "section" like this:

```
<div class="dropdown-menu" ng-style="{top: position().top+'px', left: position().left+'px'}" style="display: block;" ng-show="isOpen() && !moveInProgress" aria-hidden="{{!isOpen()}}">
    <div class="sk-dropdown-category">Fiction</div>
    <a class="dropdown-item" ng-repeat="match in matches | filter:{ model : { genre: 'fiction' } } | limitTo:5" ng-class="{active:isActive(match.model.id)}" ng-mouseenter="selectActive(match.model.id)" ng-click="selectMatch(match.model.id)" role="option" id="{{::match.id}}">
        <div uib-typeahead-match index="match.model.id" match="match" query="query" template-url="templateUrl"></div>
    </a>
    <div class="sk-dropdown-category">Non-Fiction</div>
    <a class="dropdown-item" ng-repeat="match in matches | filter:{ model : { genre: 'nonfiction' } } | limitTo:5" ng-class="{active:isActive(match.model.id)}" ng-mouseenter="selectActive(match.model.id)" ng-click="selectMatch(match.model.id)" role="option" id="{{::match.id}}">
        <div uib-typeahead-match index="match.model.id" match="match" query="query" template-url="templateUrl"></div>
    </a>
</div>
```

As you can see, I now have 2 separate `ng-repeat` directives in the template. This also means that when the controller references `$index`, there can actually be more than one of the same `$index` depending on how many `ng-repeat` directives you use.

Since the `uibTypeaheadController`'s `select()` function uses an index to select the correct item in the array, this causes issues.

Instead, I have added another attribute called `typeahead-popup-template-matcher` which simply takes a string that should map to a property name on your models in the initial array.  In most cases, this value will be your UID property (to ensure we find only 1 unique instance).

I know it is possible to have your UID property nested in your object which would break my implementation, but I was trying to go for the most simple solution at first. If you feel I should implement it in another way that allows nested UID matcher values then please let me know.

### CODE REVIEW

**Comment by icfantv** [comment]
there are potentially significant performance ramifications to consider here.  @wesleycho, thoughts?

**Comment by shank8** [comment]
I agree, if you do choose to use the "matcher" implementation, then there are slight perf ramifications because your search goes from O(1) to O(N).  Can't beat that unless we have a sorted array to begin with. Then we could get O(log(N))

**Comment by shank8** [comment]
Oh I also forgot to mention that I added a utility `$filter` method onto the `uib-typeahead-popup` scope because I was finding myself needing to run a filter in an expression inside of my template (used to hide/show the section headers if there are no results to display.. i left this code out of the example for simplicity sake). Not sure if you would have a better solution to that problem.

**Comment by wesleycho** [comment]
This seems like a hack - a better solution IMO would be to add support for grouping in the typeahead component. This use case breaks a lot of assumptions of the underlying data model, and attempts to hack around that. Any support of that assumption most likely will cause lots of bugs to manifest inside the typeahead.

The better solution is to add support for grouping, which allows for more consistent model tracking & manipulation.

**Comment by icfantv** [comment]
Grouping was talked about in #1691 and #1797.  We decided that the ui-select library (while abandoned) still works quite nicely.

**Comment by shank8** [comment]
I understand your concerns, but I was trying to abstract the problem away from implementation details and allow the developer to have more freedom when constructing their custom template without forcing them to "re-learn" how to use the directive by adding some sort of `uib-typeahead-grouping` directive.  My way is the most simple, but forces assumptions to be made about how your custom template was implemented.

**Comment by shank8** [comment]
Shall we close this?

**Comment by wesleycho** [comment]
Closing as per discussion

**Pull request closed without merging**
