### PR TITLE
fix(progress): rename to avoid conflict

### PR DESCRIPTION
**Pull request by wesleycho**
- Rename to `ui-progress` and `ui-bar`

This is for fixing #2429, but does not fix it completely. The second step is removing the offending directives, which I have scheduled for 0.14.0 to give consumers of the library adequate time to migrate over.

### CODE REVIEW

**Comment by icfantv** [comment]
What do you think about injecting the `$log` service in the offending directives and adding a warning statement about deprecation?

**Comment by wesleycho** [comment]
Already done if you check it out :P

**Comment by icfantv** [comment]
Wow.  That was really embarrassing.  I told you I was too impulsive...

**Comment by icfantv** [comment]
:+1:

**Pull request closed without merging**
