### PR TITLE
fix(demo): Modify the demo app to play nice with Angular 1.3

### LINKED ISSUE #3098: (demo) MainCtrl function does not load with Angular 1.3
The demo is broken because the MainCtrl function does not load.  The following error is logged in the console:  "MainCtrl not a function, got undefined"

Error: [ng:areq] http://errors.angularjs.org/1.3.6/ng/areq?p0=MainCtrl&p1=not%20a%20function%2C%20got%20undefined
    at Error (native)

### PR DESCRIPTION
**Pull request by realityking**
This should get the demo app itself working with 1.3 and hopefully makes testing for other issues a bit easier.

Fixes #3098

### CODE REVIEW

**Comment by mwpowellhtx** [comment]
So the docs said 1.2? Does this mean I can break the champagne and celebrate 1.3 compatibility? Thank you... :+1:

**Comment by realityking** [comment]
@mwpowellhtx Unfortunately this is only one of many necessary fixes. This one is only for the demo site, which makes testing with 1.3 a bit easier.

**Comment by stevecavanagh** [comment]
This PR is much more concise and understandable than the one I have proposed (PR #3099).  Though my PR may seem to make unnecessarily large changes, it merely rearranges the code to move the controller objects out of the global scope.  I think it would be best to fix the demo app to follow a best practice and honor the spirit of the intent for throwing the exception (https://github.com/angular/angular.js/commit/3f2232b5a181512fac23775b1df4a6ebda67d018) and not pollute the global scope.  I could certainly add a test to demonstrate that window.MainCtrl, window.DownloadCtrl, and window.SelectModulesCtrl are undefined for my PR.

**Comment by realityking** [comment]
@stevecavanagh Sorry, I hadn't seen your PR (it doesn't have the 1.3 label and I was looking only at those issues) I don't care which one gets merged, I'll leave that up to the maintainers.

**Comment by stevecavanagh** [comment]
@realityking No worries, I agree, having either one of these PRs merged would help move 1.3 compatibility forward.  It's great to see more maintainers taking a look at these issues.

**Comment by wesleycho** [comment]
Landed as aa0b6392db57d436d7c203cf05555d708c945322 - thanks!

**Pull request closed without merging**
