### PR TITLE
fix(dateParser): handle cases where baseDate is an Invalid Date

### PR DESCRIPTION
**Pull request by antoinepairet**
dateParser does not handle `Invalid Date` for `baseDate`:
````
dateParser.parse('28/11/1986', 'dd/MM/yyyy', new Date(198, 10, 28));
````

screen shot 2015-06-14 at 17 41 18

### CODE REVIEW

**Comment by wesleycho** [comment]
Just noting, this PR has some overlap with #3759.

**Comment by antoinepairet** [comment]
Thanks @wesleycho 
I did not know, I should spend more time on slack :-). This PR can be closed if yours is merged.
rgds

**Comment by cbosco** [comment]
Oops I just duplicated efforts on this too https://github.com/angular-ui/bootstrap/pull/3817

+1

**Comment by wesleycho** [comment]
Closing as relevant PR is merged.

**Pull request closed without merging**
