### PR TITLE
fix(modal): closing breaks on missing scope, 1.4

### LINKED ISSUE #3787: Modal dialog does not disappear with 0.13 and Angular 1.3 when destroying a passed scope
Angular version: 1.3.16
ui-bootstrap version: 0.13.0

This is related to, but not the same as #3633 and #3620. If you create a new scope to pass to $modal.open, it needs to be destroyed when the dialog closes to prevent memory leaks. The only event we currently get to perform this action is the result promise. However, this resolves before the closing animation is executed. If you destroy the new scope at that point, the animation cannot execute, because of its dependency on ngClass to remove the 'in' CSS class.

Here is a Plunkr that shows the behavior: http://plnkr.co/edit/yaFvaOGu1NUxkzXwfFuJ?p=preview

This same Plunkr works when using version 0.12.1, so it is a breaking change.

### LINKED ISSUE #3873: Version 0.13 - modal does not close correctly
Backdrop still remains and modal itself is still there, just with opacity of 0.  Don't think this is a duplicate of https://github.com/angular-ui/bootstrap/issues/3633 .    Does not occur with 0.12.

### PR DESCRIPTION
**Pull request by chrisirhc**
- supports Angular 1.4

Fixes #3787
Fixes #3806
Fixes #3873
Closes #3888

### CODE REVIEW

**Comment by wesleycho** [comment]
This is meant to supersede my PR, correct?

**Comment by chrisirhc** [comment]
Yes, I think it fixes the root cause of a lot of issues in the repo.

**Comment by wesleycho** [comment]
LGTM

**Comment by esion** [comment]
Thank you @chrisirhc, unfortunatly there is still a bug in your plnkr you gave http://plnkr.co/edit/R8322USvwVICHy8wjM7Y?p=preview : 

* the backdrop element is still in the DOM and prevent the modal to be open again.

Other bug in the animation : 

* the modal just shows up without animation (top to middle)
* the modal just disapears without animation (middle to top)

It requires to wait the animation is finished before removing element from DOM : I've started this hack that uses the event from $animate : https://github.com/esion/bootstrap/pull/1/files#diff-15d409302580c93c654a382e2da68396R245  
[demo](http://plnkr.co/edit/EOGddlgF36e8ZusbtJUt?p=preview)

**Comment by chrisirhc** [comment]
@esion you're right, I haven't fixed the backdrop animation. I'll make another PR for that in a bit.

**Comment by chrisirhc** [comment]
@esion , I've just submitted a PR #3899 to fix the issue you're having.
Updated Plunker: http://plnkr.co/edit/WlA6T6I63Og4Hkmk2FIh?p=preview

**Comment by vamsibassetty08** [comment]
I've tried animation off globally and inclusion ngAnimate but still the backdrop doesn't close the modal with angular 1.3.2 and angular-ui-bootstrap 0.12.0. Even I tried with angular-ui-bootstrap 0.13.0 & 0.13.1 etc but still modal doesn't close as backdrop is still present..

Any other alternatives?

**Pull request merged**
