### PR TITLE
fix(datepicker): Datepicker only accept text that matches format

### PR DESCRIPTION
**Pull request by clockworked247**
fixes issue #2886

### CODE REVIEW

**Comment by jmayday** [comment]
HI. I just found this PR. Few days ago I prepared mine, very similar one. But I haven't added additional parameter strict-date. For now I would say it's redundant one because is there really a situation when we have some date format defined (and actually we always have, don't we?) but don't want date to be scrict-parsed? I just can't imagine such requirement.

**Comment by karianna** [comment]
@clockworked247 - This fails in the travis build, can you update the PR?

**Comment by clockworked247** [comment]
@karianna - Sure. Will do.

**Comment by clockworked247** [comment]
@jmayday - I believe the changes are quite similar.  I only added the param to preserve existing functionality, so if you think it's not necessary, I'm all for your change.  Looking at the code, you're removing the fallback and relying on dateParser.parse().  That code appears to effectively do the same thing in returning undefined if the date is not valid.  So that looks good to me.

**Comment by rvanbaalen** [comment]
@clockworked247 The build is still failing. Can you please fix this PR?

**Comment by clockworked247** [comment]
@rvanbaalen My understanding was that my PR was a duplicate of #3294, so I'm OK to just close this and let the issue be hashed out there.  It seems it's under debate though.  

I'm not really following what #3417 conflicts with the change.  Considering we need to validate a date entered manually in the associated text field, it only makes sense to add this kind of change.  Otherwise, the Date() fallback will just change the invalid date to some odd number that has nothing to do with what the user entered.  Super confusing...

Closing this, as it's a duplicate.

**Comment by rvanbaalen** [comment]
Thanks for detecting the duplicate @clockworked247 :+1:

**Pull request closed without merging**
