### PR TITLE
refactor(datepicker): optimize datepicker

### LINKED ISSUE #3451: DatePicker - Performance issues with popup + other stuff
Using one of Chromes add-ons for performance evaluation, I have seen this:

image

I have only one datepicker (if I am not mistaken) in sight, so this is quite disturbing...
I cannot imagine what happens with more...
Do you think it would be possible to remove the popup from the DOM when it is not needed to be visible?
I think that would help a lot.
(I am referring mainly to `datepickerPopup`, but it may apply to other places as well)

---

Also, the popup doesn't work so good when placed inside some containers having CSS positioning and floating.
If you could make it work good in all cases (e.g. positioning it with JS) it would be nice.
(Then you might face problems with scrolling while the popup is open, but that's bearable)

---

Also, another issue:
I was using an old version of your library and I came across some issues with the week numbers.
I have found a correct version of the `getISO8601WeekNumber()` that you use:

```
Date.prototype.getWeekNumber = function () {
    var d = new Date(+this);
    d.setHours(0, 0, 0);
    d.setDate(d.getDate() + 4 - (d.getDay() || 7));
    return Math.ceil((((d - new Date(d.getFullYear(), 0, 1)) / 8.64e7) + 1) / 7);
};
```

I have noticed that in newer versions of you lib, you have improved this function, but I think it is still not the same to the one I use.
If you like, take a look at this implementation and compare, just to make sure you got it right.

### PR DESCRIPTION
**Pull request by wesleycho**
- Add new class manipulation helper directive that uses 1 watcher as opposed to watchers for each element with ng-class
- Optimize disabled state
- Optimize class binding

This supercedes #3770, and resolves #3451 & #2613

### CODE REVIEW

**Comment by Foxandxss** [comment]
A couple of times checking this PR and I have no idea what you're trying to accomplish in here.

If this are 3 changes, please, create 3 PRs because I am getting confused.

The new `uibIsClass`, I don't understand what you want to do with it or how it relates to the datepicker at all.

If possible, close this, create as many PRs as you need and for the one for the uibIsClass, give a good explanation of why we need it (apart from ng-class creating too many watches) and some real world examples in how to use it (because the PR is not touching the datepicker for that).

Cheers :)

**Comment by wesleycho** [comment]
The original changes were in 3 commits - it was actually a bit tricky to parse it out, although they were in separate commits. `master` has changed a lot since then and conflicts need to be resolved.

The `isClass` change allows you to add only 1 $watch for ng-class behavior across an ng-repeat, as opposed to n $watches when using ng-repeat + ng-class.

The change to use Object.defineProperty removes updates of properties on the `$scope.watchData` object in the popup for use in the datepicker to avoid adding additional $watchers.

And lastly, a one-way binding on the datepicker disabled attribute since the isClass change requires elimination of use of track by.

**Comment by Foxandxss** [comment]
But how is the isClass used in the datepicker?

**Comment by wesleycho** [comment]
Something weird happened - let me push up the other changes necessary to the template.

**Comment by Foxandxss** [comment]
I desist. This PR gives me headache. That isClass has an horrible syntax and combined with a ng-repeat, makes the code tests to understand.

I hope this cuts enough watchers to make it worthwile.

**Pull request closed without merging**
